### PR TITLE
refine H4 endpoint, add tests

### LINKED ISSUE #4841: Remove sort expression for Schedule H4
### What we’re after

sort_expression has been removed for schedule B. Should the sort_expression for schedule H4 be removed? 

https://github.com/fecgov/openFEC/blob/develop/webservices/common/models/itemized.py#L897

### Related ticket(s)

[PR for schedule B #4509](https://github.com/fecgov/openFEC/pull/4509)

### Completion criteria

- [ ] Remove sort expression

### LINKED ISSUE #5361: Refine H4 Endpoint, Build MV
### What we’re after

We need to do some refinement of the current H4 endpoint prototype. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] https://github.com/fecgov/openFEC/issues/5360

### Action item(s)
- [x] Build an MV as the endpoint is currently pulling directly from the table
- [ ] Add more filters, rename current filters
- [x] Add missing parameters and rename currently confusing parameters
- [x] Have discussion about pulling in committee level info? 

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)
- [ ] The current beta endpoint is ready for implementation when the contractors' work is complete

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary 

- Resolves #5361 
- Resolves #4841 

 This ticket refines and deploys the H4 endpoint. I added tsvector filters for payee_name and disbursement_purpose, edited the other filters, added some automated testing, and removed the sort_expression logic. 

This should allow for @JonellaCulmer's design [here](https://app.mural.co/t/fec4461/m/fec4461/1680123342880/4b23fc49994eb22d3479d0407543d334ac42e044?sender=a8d29361-79af-49ec-a9b3-f5560b7ef3c5)

### Required reviewers

2 devs

## Impacted areas of the application

-  H4 endpoint

## Screenshots

Screen Shot 2023-04-11 at 8 34 46 AM

## How to test

Here's the[ data mapping PR](https://github.com/fecgov/openFEC/issues/5360) for reference and here's the [map doc](https://docs.google.com/document/d/1_0SqudoNoAXBdauhDkhalW3LIYbyqPo_HU6aY8VOg4Y/edit)

I have locust tested it and didn't see a large change. 

- `pyenv virtualenv 3.9.15 api15`
- `pyenv activate api15`
- `dropdb cfdm_test`
-  `createdb cfdm_test`
- `invoke create_sample_db`
-  http://127.0.0.1:5000/v1/schedules/schedule_h4/?q_disbursement_purpose=admin&sort_hide_null=false&sort_null_only=false&sort=event_purpose_date&per_page=20
- http://127.0.0.1:5000/v1/schedules/schedule_h4/?&sort_hide_null=false&sort_null_only=false&sort=event_purpose_date&per_page=20

It's currently on dev:
https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_h4/?q_payee_name=Fed&sort=-event_purpose_date&sort_null_only=false&sort_hide_null=false&per_page=20
(28418 results)

### CODE REVIEW

**Review by pkfec — COMMENTED** [review]
@cnlucas `tablename`  is enough since this model is now switched to an MV. Can you remove the `table_args` here?

**Comment by fec-jli** [comment]
Please remove "sort_expressions" section in sorting.py line 98 -L111. we don't need it. Thanks

**Review by fec-jli — APPROVED** [review]
Great Work. Thanks

**Review by tmpayton — APPROVED** [review]
Nice work!

**Review by pkfec — APPROVED** [review]
Thanks for making the required changes @cnlucas!

**Pull request merged**
