### PR TITLE
[Do not merge before PR#3688 due to migration number]Fix bernie sanders totals incorrect

### LINKED ISSUE #3700: Bernie Sanders totals incorrect
*********Checking: P60007168, SANDERS, BERNARD ************

datatable_url
https://api.open.fec.gov/v1/candidates/totals/?candidate_id=P60007168&election_year=2020&election_full=true&api_key=DEMO_KEY&sort=-receipts

candidate_profile_url
https://api.open.fec.gov/v1/candidate/P60007168/totals/?cycle=2020&api_key=DEMO_KEY&full_election=True

election_profile_url
https://api.open.fec.gov/v1/elections/?candidate_id=P60007168&cycle=2020&election_full=true&api_key=DEMO_KEY&office=president&sort_nulls_last=true&sort=-total_receipts&per_page=100

!!! ERROR - receipts don't match!!!
Candidate datatable: 	$20,700,446.12
Candidate profile page: $20,817,691.10
Election profile page: 	$20,700,446.12

!!! ERROR - disbursements don't match!!!
Candidate datatable: 	$7,593,817.33
Candidate profile page: $8,422,503.45
Election profile page: 	$7,593,817.33\

It looks like the candidate's 2016 committee's 2017 activity is being included in the candidate totals.

### PR DESCRIPTION
**Pull request by fecjjeng**
## Summary (required)
- Resolves #3700
Bernie Sanders totals incorrect

## How to test the changes locally
-Download the branch feature/3700-fix-BernieSanders-totals-incorrect, run migration files V0131 and V0132 (or run invoke create_sample_db) to make sure migration files runs without error.

Two tmp materialized views had been created in DEV database that has the updated MVs logic.
(Note: ofec_candidate_totals_mv_tmp references ofec_cand_cmte_linkage_mv_tmp)
public.ofec_cand_cmte_linkage_mv_tmp
public.ofec_candidate_totals_mv_tmp

- To test database:
(Cand_id: 
 'P60007168':  Bernie Sandersn (runs 2016, 2020)
make sure 2018 cycle financial data is calculated as part of election_cycle 2020, not 2016)

 'P00003392': Hillary Clinton (runs 2008, 2016)
make sure 2014 cycle financial data  is calculated as part of election_cycle 2016, not 2008; 2010, 2012, 2018, and 2020 cycle data should not be calculated as part of neither election_cycle 2008 nor 2016.

--Connect to DEV database, 
SELECT ofec_cand_cmte_linkage_mv_tmp.cand_id,
  ofec_cand_cmte_linkage_mv_tmp.election_yr_to_be_included as election_yr_to_be_included,
  ofec_cand_cmte_linkage_mv_tmp.fec_election_yr,
  ofec_cand_cmte_linkage_mv_tmp.cmte_id
FROM ofec_cand_cmte_linkage_mv_tmp
WHERE ofec_cand_cmte_linkage_mv_tmp.cmte_dsgn::text = ANY (ARRAY['P'::character varying::text, 'A'::character varying::text])
and cand_id = 'P60007168'
--and cand_id = 'P00003392'
group by ofec_cand_cmte_linkage_mv_tmp.cand_id,
  ofec_cand_cmte_linkage_mv_tmp.election_yr_to_be_included,
  ofec_cand_cmte_linkage_mv_tmp.fec_election_yr,
  ofec_cand_cmte_linkage_mv_tmp.cmte_id 
order by election_yr_to_be_included, fec_election_yr;

select *
from public.ofec_candidate_totals_mv_tmp
where candidate_id = 'P60007168'
--where candidate_id = 'P00003392'
order by election_year, cycle, is_election;

- To test API: 
In models/candidates.py file, make the following changes:
    In class CandidateTotal:
    __tablename__ = 'ofec_candidate_totals_mv_tmp'

    In class Candidate:
replace ofec_cand_cmte_linkage_mv with ofec_cand_cmte_linkage_mv_tmp in
secondaryjoin=
secondaryjoin=
order_by= 

In models/links/py file, make the following changes:
In class CandidateCommitteeLink:
__tablename__ = 'ofec_cand_cmte_linkage_mv_tmp'

Point to the DEV database and start the local server.  

For /candidate/totals endpoint:
candidate_id: P60007168
election_year: 2020
election_full: true

candidate_id: P00003392
election_year: 2016
election_full: true

For /elections/  endpoint:
cycle: 2020
election_full: true
office: president
(bernie sanders is the second entry, with total receipts = 20817691.1)

cycle: 2016
election_full: true
office: president
(Hillary Clinton is the first entry, with total receipts = 585699061.27)

## Impacted areas of the application
List general components of the application that this PR will affect:

The following two endpoints would be impacted
(the API interface does not change, but the data output will be updated)
/candidate/totals
/elections/ 

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

### CODE REVIEW

**Comment by pkfec** [comment]
@hcaofec @lbeaufort can you review this PR when you get a chance?

**Comment by hcaofec** [comment]
followed testing instructions on local, and look good. 
V_0132, line 51, this subquery cycle_cmte_totals_basic may not be needed since analytic functions have already been applied in ofec_totals_house_senate_vw and ofec_totals_presidential_vw.
Screen Shot 2019-04-30 at 12 06 26 AM

**Comment by fecjjeng** [comment]
There is no analytic functions applied in ofec_totals_house_senate_mv and ofec_totals_presidential_mv.  Even if there are, that is per form based.

If a committee submit both F3 and F3P, it is true that the running total should be committee specific, not form_type specific. _IF_ committee submit both form with the same coverage date.  However, if committees submit F3 and F3P with different ending coverage date, then it would resulted in difference.  
Having said that, it is true that all the entries currently in the MVs happened to have the same converage_end_date and hence the running total are the same.  We had this discussion on this when working with issue #3635 that we would like have this layer of logic to catch the situation when it happen.

**Comment by hcaofec** [comment]
Another thought for V0132 is  election_total can be calculated based on cycle_total. It does not need to go to per cmte level again since that is already calculated in cycle_total.  This may have benefits for less complexity and easy maintenance.

These comments are all thoughts for the future if we ever want to refine this view.
It will not affect the approval of this PR though.

https://github.com/fecgov/openFEC/pull/3726/files#diff-5e70a644b24fb447facc40fadcc30a4bR110

**Comment by hcaofec** [comment]
Back to the F3 and F3P case,  when I say analytic functions applied in ofec_totals_house_senate_mv and ofec_totals_presidential_mv, I meant to to say the analytic applications are applied in the ofec_totals_combined_mv which is the basis of the other two mvs.

And in ofec_totals_combined_mv,  last_coh...etc is calculated on cmte+cycle level, not form based.   That's why the example above shows same coverage end date and image number.   The F3 and F3P  have different cvg_end_dt in v_sum.  These are different  rpt_tp.

Here is V_SUM table:
Screen Shot 2019-04-30 at 11 15 10 AM

**Comment by hcaofec** [comment]
Here is OFEC_TOTALS_COMBINED_MV:

Screen Shot 2019-04-30 at 11 17 02 AM

F3 ttl_receipts: 83825.05 + 187588.60 = 271413.65
F3P ttl_receipts added together:  5874365.79

But all the running values are calculated across cmte and cycle, regardless form type.  When coming down to the final output, the aggregates is calculated on cmte, cycle and form_type level.

**Comment by fecjjeng** [comment]
Yes, you are correct.  I only recalled that totals_combined are grouped on form_tp.  But forgot we went back to check to previous calculation and realized the total/running total are on the committee based.

**Pull request merged**
