### PR TITLE
Feature/upgrade elasticsearch

### PR DESCRIPTION
**Pull request by fec-jli**
upgrade elasticsearch 24 —> 56

### CODE REVIEW

**Comment by vrajmohan** [comment]
It is a good practice to clean up all the commits on the branch so that the changes tell a story. `git rebase -i` is a useful tool. It is also nice to have only stable commits, ie, no commits should result in compilation errors or failing tests.

**Comment by vrajmohan** [comment]
Is the SHARD_SETTING change really needed? If it is, some documentation in the commit would be useful as to why it is needed and why the defaults are not sufficient.

**Comment by vrajmohan** [comment]
https://github.com/fecgov/openFEC/pull/3084/commits/6a999eb75000b1644b4a110c3f9612c345bf7e3d should be dropped.

**Comment by vrajmohan** [comment]
In https://github.com/fecgov/openFEC/pull/3084/commits/75cd9c2e7c11f6b440a9a3e7bb34f61443f8e4ed, the commit message does not seem to match the changes.

**Comment by vrajmohan** [comment]
https://github.com/fecgov/openFEC/pull/3084/commits/37df2470b0b8be6d6ed55a59c081a5d0fd02466d and https://github.com/fecgov/openFEC/pull/3084/commits/af312ff1e32d4c54785a186b62d6ccdddad76713 can be squashed together to make it easier to understand.

**Comment by vrajmohan** [comment]
We should connect this PR to the appropriate issue - that way, we will not miss tasks captured there, e.g., load testing.

**Comment by fec-jli** [comment]
for SHARD_SETTIN, I checked dev space, we have 6 nodes now.
One index in Elasticsearch is allotted five primary shards by default. That means that we can spread that index out over a maximum of five nodes, with one shard on each node (still have one more:). That’s a lot of capacity, so we don't need worry about it now. Thanks
[https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_basic_concepts.html](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/_basic_concepts.html)

**Comment by fec-jli** [comment]
*Practice to clean up the commits*
1)Change commit 75cd9c message:
     a)git rebase -i HEAD~2
     b)Change “pick” to “reword” for 75cd9c
     c)input new message for 75cd9c
     d)git push --force

2)Squashing 37df247 and af312ff (change to 808a3):
   a)git rebase -i HEAD~8
   b)modify:
       (pick) 37df2470b0b8be6d6ed55a59c081a5d0fd02466d
       (squash) 808a35def7f29e20c3dc9f05ab0a85f2aee3b324
   c)git push --force

3)note: after squashed two commits ( one is the latest, another is the oldest), then all middle commits are missing, so I have to push one more commit for requirement.txt to use elasticsearch56 library.

**Comment by vrajmohan** [comment]
Nice work. Looks good to me. Did we complete load testing?

**Comment by fec-jli** [comment]
I am going to load all current murs and AOs today. we just load all data into db recently.
almost sync with prod db.Thanks

**Comment by vrajmohan** [comment]
Sorry, I meant testing that the system performs at least as well as 2.4 when multiple users are searching the index at the same time - the 7th checklist item in the original issue.

**Comment by fec-jli** [comment]
yup, we need run locust to compare es2.4. Thanks

**Comment by fec-jli** [comment]
I run locust on local,  50users/10rate. the speed is a little bit faster on ES56 for legal_search:

ES24:
es24_local_50_10_test_result


ES56:
es56_local_50_10_test_result

**Pull request merged**
