### PR TITLE
remove unused python libraries 

### LINKED ISSUE #3955: remove unused libraries
## Summary
Related issue #3940 and #3782. Need to remove unused python libraries (but need to double check each is not in use before removing them from requirements). `pandas` will require removal of unused functions that reference the package.

|     package     |      location       |    current | newest | has_bkwrd_incompatible |
|  ---  |  ---  |  ---  |  ---  | --- |
| [unused] [`prompt-toolkit`](https://python-prompt-toolkit.readthedocs.io/en/master/pages/upgrading/3.0.html) | `requirements.txt` | 2.0.6 | 3.0.0 | true |
| [unused] `ipython` | `requirements-dev.txt` | 7.5.0 | 
| [unused] [`faker`](https://github.com/joke2k/faker/blob/master/CHANGELOG.rst) | `requirements-dev.txt` | 0.7.18 | 2.0.1 | true |
| [unused] `pdbpp` | `requirements-dev.txt` | 0.9.1 |
| [unused] `pygments` | `requirements-dev.txt` | 2.2.0 |
| [unused] [`pandas`](https://pandas.pydata.org/pandas-docs/stable/whatsnew/index.html) |  `requirements-dev.txt` | 0.16.2 |  0.25.0 | true |
| [unused] `xlrd` | `requirements-dev.txt` | 0.9.4 |

## Completion Criteria ##
- [ ] Remove packages
- [ ] Test the removal.

### PR DESCRIPTION
**Pull request by pkfec**
## Summary (required)

- Resolves #3955 

_Include a summary of proposed changes._

1. Removed one unused python packages from requirements.txt.
   - prompt-toolkit 
2. Removed the unused python packages from requirements-dev.txt.
   - ipython 
   - faker 
   - pygments
   - pandas 
   - xlrd
3. pandas package was mainly used  to extract and load data into few table by running the python scripts in `manage.py` via command line. We can automate the data loads in a migration file and run across all our environments. Removed the python scripts that load  data in manage.py. Also deleted the unused dump files from the repo.

## How to test the changes locally

- checkout branch `feature/3955-remove-unused-pkgs` 
- run `pip install -r requirements.txt` 
- run `pip install -r requirements-dev.txt` 
- run `pytest` (all tests should pass)
- export `SQLA_CONN` to point to dev/ stage or prod db
- start server
- test API endpoints. Make sure there are no errors in the terminal.
- test CMS-API interaction.

### CODE REVIEW

**Comment by fec-jli** [comment]
I prefer to keep iPython. Thanks

**Comment by pkfec** [comment]
@fec-jli  `ipython` is an interactive python shell. It has features like syntax highlighting, tab completion, proper indentation and many more than default python interpreter. We  can always  install this pkg if we want, however I do not see this pkg being used for our development needs.

**Comment by pkfec** [comment]
> I prefer to keep iPython. Thanks

@fec-jli ipython is an interactive python shell. It has features like syntax highlighting, tab completion, proper indentation and many more than default python interpreter. We can always install this pkg if we want, however I do not see this pkg being used for our development needs.

**Comment by fec-jli** [comment]
I need iPython to test some codes. Thanks

**Comment by pkfec** [comment]
> I need iPython to test some codes. Thanks

You can still test your code with default python interpreter. It is just how you prefer to write your code on a terminal using the standard  or enhanced library with more options. I guess my point here is we could still keep this package if we really need it , but its not a must have package.

**Comment by lbeaufort** [comment]
@fec-jli says she is ok with removing `ipython` from requirements-dev and installing `ipython` on her local if she needs it.

**Pull request merged**
