### PR TITLE
Add form2 endpoint /efile/form2/

### LINKED ISSUE #5577: Add state to efilings
### What we’re after

Follow-up work to this ticket https://github.com/fecgov/openFEC/issues/5497 we should add state and a state filter to the efilings endpoint. There's currently some discussion about how best to go about this-- and if a form 2/candidates efile endpoint might be a better fit

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [ ] https://github.com/fecgov/openFEC/issues/5497

### Action item(s)
- [ ] Research adding el_state and/or c_state to efilings 

### Completion criteria
- [ ] We have a state field and state filter for form 2 raw filings.

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary (required)

- Resolves #5577 

Our candidate endpoint is 1-3 days behind the raw efiling endpoint due to the nightly process. Users have requested more fields/filings on our efiling endpoint so that they could see the candidates that filed in their state in real time. This PR builds out an efiling form2 endpoint so that users can access form2 data in real time. 

### Required reviewers

1-2 devs, 1 PM

## Impacted areas of the application

-  efiling endpoint

## How to test
activate your env
pytest
flask run
http://127.0.0.1:5000/v1/efile/form2/?page=1&per_page=20&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/efile/form2/?page=1&per_page=20&min_load_timestamp=1%2F1%2F2024&max_load_timestamp=2%2F2%2F2024&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/efile/form2/?page=1&per_page=20&candidate_office=P&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/efile/form2/?page=1&per_page=20&election_state=UT&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/efile/form2/?page=1&per_page=20&candidate_id=H2CA18148&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/efile/form2/?page=1&per_page=20&file_number=1747369&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

DEV: 
[Show based on min and max timestamps](https://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&min_load_timestamp=1%2F1%2F2024&max_load_timestamp=2%2F2%2F2024&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)
    [Show based on candidate ID](https://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&candidate_id=H2CA18148&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)
    [Show based on file_number](https://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&file_number=1747369&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)

Also here's my load testing document. I didn't find any degradation in performance with the new code and with new form2 queries. They were my final tests and were average. Please let me know if you have any questions. 
https://docs.google.com/spreadsheets/d/1tnOmnkxy66PKGpQGtt4zSjLzwJO9_OuPSisGoqtdASM/edit#gid=0

### CODE REVIEW

**Comment by patphongs** [comment]
@cnlucas Thanks for letting me test on dev. I got results for some of the queries, but no results for the following list. Do you know if that's expected since maybe it's the dev environment? or am I doing something wrong?

- [Show based on min and max timestamps](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&min_load_timestamp=1%2F1%2F2017&max_load_timestamp=1%2F1%2F2018&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false) 
- [Show based on candidate ID](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&candidate_id=H8UT03477&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)
- [Show based on file_number](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&file_number=1230383&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)

**Review by patphongs — COMMENTED** [review]
@cnlucas Thanks for letting me test on dev. I got results for some of the queries, but no results for the following list. Do you know if that's expected since maybe it's the dev environment? or am I doing something wrong?

- [Show based on min and max timestamps](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&min_load_timestamp=1%2F1%2F2017&max_load_timestamp=1%2F1%2F2018&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false) 
- [Show based on candidate ID](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&candidate_id=H8UT03477&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)
- [Show based on file_number](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&file_number=1230383&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)

**Comment by cnlucas** [comment]
> @cnlucas Thanks for letting me test on dev. I got results for some of the queries, but no results for the following list. Do you know if that's expected since maybe it's the dev environment? or am I doing something wrong?
> 
>     * [Show based on min and max timestamps](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&min_load_timestamp=1%2F1%2F2017&max_load_timestamp=1%2F1%2F2018&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)
> 
>     * [Show based on candidate ID](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&candidate_id=H8UT03477&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)
> 
>     * [Show based on file_number](http://fec-dev-api.app.cloud.gov/v1/efile/form2/?page=1&per_page=20&file_number=1230383&sort=-load_timestamp&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false)

Thanks @patphongs, I added dev links for the filters you mentioned to the PR.

**Review by patphongs — APPROVED** [review]
Looks great and all filters work well, thanks @cnlucas!

**Review by tmpayton — APPROVED** [review]
Really awesome job!

**Review by fec-jli — APPROVED** [review]
It works as expected. good job. Thanks

**Pull request merged**
