### PR TITLE
Add leadership pac committee rows in return result

### LINKED ISSUE #4738: Add leadership PACs rows  to CommitteeHistoryView when filtering by candidate_id
To display leadership PAC names on candidate profile page, we need add leadership PACs committee rows in endpoint: `/candidate/<string:candidate_id>/committees/history/<int:cycle>/`

Ref [https://github.com/fecgov/fec-cms/issues/4270](https://github.com/fecgov/fec-cms/issues/4270)

Completion Criteria:
- [x] Add a new sponsor_candidate_id filter to CommitteeHistoryView
- [x] add pytest

### PR DESCRIPTION
**Pull request by fec-jli**
## Summary (required)
To display leadership PAC names on candidate profile page, we need add leadership PACs committee rows in endpoint: /candidate/<string:candidate_id>/committees/history/<int:cycle>/

- Resolves #4738

_Include a summary of proposed changes._
[https://docs.google.com/drawings/d/1eROcEyNgXaKsRC39gQC9AUMfnd2EvYWKGWQqD_T1j9E/edit](https://docs.google.com/drawings/d/1eROcEyNgXaKsRC39gQC9AUMfnd2EvYWKGWQqD_T1j9E/edit)
Screen Shot 2021-01-24 at 11 29 03 PM

## How to test the changes locally
1) checkout branch, point to dev db
2) pytest
3) test / compare example endpoints on both local and prod:
[https://docs.google.com/spreadsheets/d/1cxZ1kFQP72Yi88cfjbJmV5A0s0UYD_jV/edit#gid=758020012](https://docs.google.com/spreadsheets/d/1cxZ1kFQP72Yi88cfjbJmV5A0s0UYD_jV/edit#gid=758020012)

example 1:
local: http://127.0.0.1:5000/v1/candidate/S4AR00103/committees/history/2020/	
prod: https://api.open.fec.gov/v1/candidate/S4AR00103/committees/history/2020?election_full=true&api_key=DEMO_KEY
Screen Shot 2021-01-25 at 12 09 36 AM

example 2:
local: http://127.0.0.1:5000/v1/candidate/P00009092/committees/history/2020/
prod: https://api.open.fec.gov/v1/candidate/P00009092/committees/history/2020/?election_full=true&api_key=DEMO_KEY
Screen Shot 2021-01-25 at 10 03 06 AM
	
example 3:
local: http://127.0.0.1:5000/v1/candidate/H0MI08042/committees/history/2014/
prod: https://api.open.fec.gov/v1/candidate/H0MI08042/committees/history/2014/?election_full=true&api_key=DEMO_KEY
Screen Shot 2021-01-25 at 10 03 18 AM

example 4:
local: http://127.0.0.1:5000/v1/candidate/P00009183/committees/history/2020/
prod: https://api.open.fec.gov/v1/candidate/P00009183/committees/history/2020/?election_full=true&api_key=DEMO_KEY
Screen Shot 2021-01-25 at 10 03 30 AM

example 5:
local: http://127.0.0.1:5000/v1/candidate/H0OH08029/committees/history/2016/
prod: https://api.open.fec.gov/v1/candidate/H0OH08029/committees/history/2016/?election_full=true&api_key=DEMO_KEY
Screen Shot 2021-01-25 at 10 03 46 AM

-

## Impacted areas of the application
List general components of the application that this PR will affect:
endpoints:
'/candidate/<candidate_id>/committees/history/', '/candidate/<candidate_id>/committees/history/<int:cycle>/',
 
## Reviewer
one backend developer and one database developer

### CODE REVIEW

**Comment by fec-jli** [comment]
Final query:
SELECT anon_1.ofec_committee_history_mv_idx, anon_1.ofec_committee_history_mv_name, anon_1.ofec_committee_history_mv_committee_id, anon_1.ofec_committee_history_mv_cycles, anon_1.ofec_committee_history_mv_treasurer_name, 
....
anon_1.ofec_committee_history_mv_convert_to_pac_flag, anon_1.ofec_committee_history_mv_sponsor_candidate_ids 
FROM (
	(SELECT DISTINCT ON (ofec_committee_history_mv.committee_id) ofec_committee_history_mv.idx AS ofec_committee_history_mv_idx, ofec_committee_history_mv.name AS ofec_committee_history_mv_name, ofec_committee_history_mv.committee_id AS ofec_committee_history_mv_committee_id, 
	....
	ofec_committee_history_mv.convert_to_pac_flag AS ofec_committee_history_mv_convert_to_pac_flag, ofec_committee_history_mv.sponsor_candidate_ids AS ofec_committee_history_mv_sponsor_candidate_ids 
	FROM ofec_committee_history_mv JOIN ofec_cand_cmte_linkage_mv 
	ON ofec_cand_cmte_linkage_mv.cmte_id = ofec_committee_history_mv.committee_id
	AND ofec_cand_cmte_linkage_mv.fec_election_yr = ofec_committee_history_mv.cycle 
	WHERE ofec_cand_cmte_linkage_mv.cand_id = 'S4AR00103' 
	AND ofec_cand_cmte_linkage_mv.election_yr_to_be_included = 2020 
	ORDER BY ofec_committee_history_mv.committee_id, ofec_committee_history_mv.cycle DESC) 

	UNION 
	(SELECT DISTINCT ON (ofec_committee_history_mv.committee_id) ofec_committee_history_mv.idx AS ofec_committee_history_mv_idx, ofec_committee_history_mv.name AS ofec_committee_history_mv_name, ofec_committee_history_mv.committee_id AS ofec_committee_history_mv_committee_id, 
	....
	ofec_committee_history_mv.convert_to_pac_flag AS ofec_committee_history_mv_convert_to_pac_flag, ofec_committee_history_mv.sponsor_candidate_ids AS ofec_committee_history_mv_sponsor_candidate_ids 
	FROM ofec_committee_history_mv JOIN disclosure.cand_cmte_linkage_alternate 
	ON disclosure.cand_cmte_linkage_alternate.cmte_id = ofec_committee_history_mv.committee_id 
	AND disclosure.cand_cmte_linkage_alternate.fec_election_yr = ofec_committee_history_mv.cycle 
	WHERE disclosure.cand_cmte_linkage_alternate.cand_id = 'S4AR00103' 
	AND disclosure.cand_cmte_linkage_alternate.cand_election_yr = 2020 
	ORDER BY ofec_committee_history_mv.committee_id, ofec_committee_history_mv.cycle DESC) 
	
	UNION 
	(SELECT DISTINCT ON (ofec_committee_history_mv.committee_id) ofec_committee_history_mv.idx AS ofec_committee_history_mv_idx, ofec_committee_history_mv.name AS ofec_committee_history_mv_name, ofec_committee_history_mv.committee_id AS ofec_committee_history_mv_committee_id, 
	....
	ofec_committee_history_mv.convert_to_pac_flag AS ofec_committee_history_mv_convert_to_pac_flag, ofec_committee_history_mv.sponsor_candidate_ids AS ofec_committee_history_mv_sponsor_candidate_ids 
	FROM ofec_committee_history_mv 
	WHERE ofec_committee_history_mv.former_candidate_id = 'S4AR00103' 
	AND ofec_committee_history_mv.former_candidate_election_year = 2020 
	ORDER BY ofec_committee_history_mv.committee_id, ofec_committee_history_mv.cycle DESC)
) AS anon_1 
ORDER BY anon_1.ofec_committee_history_mv_committee_id, anon_1.ofec_committee_history_mv_cycle DESC

**Review by hcaofec — APPROVED** [review]
Followed the test instruction and all looks good.  So approved.

**Review by pkfec — APPROVED** [review]
@fec-jli Thanks for documenting different candidate/committee scenarios. They are very helpful during testing.

**Comment by fec-jli** [comment]
Notes:
this two candidates (P00009183,  P00006213) cand_election_yr=2020 and fec_election_yr=2022
will show leadership pac.
SELECT * FROM disclosure.cand_cmte_linkage_alternate
where fec_election_yr=2022 and cand_id like ‘P%’
Screen Shot 2021-01-26 at 1 09 41 PM

**Pull request merged**
