### PR TITLE
Feature/4073 update flask dependencies

### LINKED ISSUE #4073: [python package update] flask-related dependencies
### Summary
from #3953 team discussed organizing package updates with logical groupings. The logic of the groupings below is that they all relate to `Flask` (updated via #4026 ). These should also have no breaking changes. The team agreed that each library should have a single commit and each commit should have a single library (1:1)
• Flask (dependency of flask-apispec, flask-cors, flask-restful, flask-script, flask-sqlalechmy, nplusone)
### Completion criteria
- [ ] package verified to have no breaking changes in the way we use them
- [ ] package is updated and tested
- [ ] 1:1 package to commit

### PR DESCRIPTION
**Pull request by jason-upchurch**
## Note to reviewers:
selected 3 reviewers but any one reviewer is sufficient.

## Summary (required)
- Updates minor package versions for flask-related dependencies.
- Resolves #4073 

## How to test locally
- check out branch
- `pip install -r requirements.txt`
- `pytest`
- run local api and check an endpoint

## Impacted areas of the application
List general components of the application that this PR will affect:
-  `Flask`

### CODE REVIEW

**Comment by fec-jli** [comment]
After I setup local api based on this branch.
there are a couple of endpoints not working: ( I run endpoints_walk.py and got these)
/communication_costs/by_candidate/
/committee/{committee_id}/communication_costs/by_candidate/
/electioneering/by_candidate/
/committee/{committee_id}/electioneering/by_candidate/
Could you look at them? Thanks

**Comment by jason-upchurch** [comment]
Hi @fec-jli ,
Just going through these one by one... What is the problem you see with `/communication_costs/by_candidate/`? I am able to view that endpoint on the feature branch (I pass a candidate id): http://localhost:5000/developers/#/communication%20cost/get_communication_costs_by_candidate_

**Comment by jason-upchurch** [comment]
@fec-jli, I don't think the problem you are seeing was introduced by this branch. For example, if you create a clean python environment and use develop, the following errors are generated from endpoints_walk.py:

```
******/communication_costs/by_candidate/?api_key={api_key}: not working. Status: 422
******/committee/{committee_id}/communication_costs/by_candidate/?api_key={api_key}: not working. Status: 422
******/electioneering/by_candidate/?api_key={api_key}: not working. Status: 422
******/committee/{committee_id}/electioneering/by_candidate/?api_key={api_key}: not working. Status: 422
```
Is this file being actively maintained?

**Comment by jason-upchurch** [comment]
@fec-jli @lbeaufort @pkfec , Jun has approved this PR. I am fine with one reviewer on this, but if others want to review that's cool too. If not, is someone able to merge? Many thanks all.

**Pull request merged**
