### PR TITLE
Feature/refresh mvs

### PR DESCRIPTION
**Pull request by vrajmohan**
Ensure that materialized views are populated with data in `sample db`.

Most materialized views have data after running `python manage.py refresh_materialized` automatically.

To close this issue, we have to fix those that do not.

### CODE REVIEW

**Comment by vrajmohan** [comment]
@fecjjeng, I suggest we review and merge this PR as it takes a big step forward. The remaining MVs that need to be populated are tracked in separate tickets.

**Comment by fecjjeng** [comment]
@vraj Is PR#3107 still WIP?  The changes updated quite a few MV definitions in the migration files so they will be created with data.  Some others seems just formatting changes.  Is it correct?




On May 7, 2018, at 8:10 PM, R Vrajmohan <notifications@github.com<mailto:notifications@github.com>> wrote:


@vrajmohan<https://github.com/vrajmohan> requested your review on: fecgov/openFEC#3107<https://github.com/fecgov/openFEC/pull/3107> Feature/refresh mvs.

**Comment by vrajmohan** [comment]
It is no longer WIP. Yes, those changes are correct + one more change to `tasks.py`.

**Comment by fecjjeng** [comment]
Thanks.


On May 8, 2018, at 3:04 PM, R Vrajmohan <notifications@github.com<mailto:notifications@github.com>> wrote:


It is no longer WIP. Yes, those changes are correct + one more change to tasks.py.

**Comment by fecjjeng** [comment]
I will do so.

**Comment by vrajmohan** [comment]
```
Usage: inv[oke] [--core-opts] create_sample_db [other tasks here ...]

Docstring:
  Load schema and data into the empty database pointed to by $SQLA_SAMPLE_DB_CONN
```

The change in `tasks.py` runs `python manage.py refresh_materialized` at the end of `invoke create_sample_db` so that some of the materialized views are populated as identified in https://github.com/fecgov/openFEC/issues/3062#issuecomment-387245778

**Pull request merged**
