### PR TITLE
Run `npm audit fix`

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

- Resolves #https://github.com/fecgov/fec-accounts/issues/384

Run `npm audit fix`

### Required reviewers

One developer

## Impacted areas of the application

General components of the application that this PR will affect:

-  Swagger docs

### How to review
- Check out this branch, `npm i` and run the API locally, test swagger docs
- Deploy to `dev` and test there (currently on `dev` as of 7/14/21, 12:30pm: https://fec-dev-api.app.cloud.gov/developers/), test swagger docs

### CODE REVIEW

**Comment by rfultz** [comment]
Any tips on how to review this? Looking at the changes, it's just minor- and patch-level updates so things should be fine

**Comment by lbeaufort** [comment]
> Any tips on how to review this? Looking at the changes, it's just minor- and patch-level updates so things should be fine

Sorry about that @rfultz I updated the PR: 
### How to review
- Check out this branch, `npm i` and run the API locally
- Deploy to `dev` and test there (currently on `dev` as of 7/14/21, 12:30pm: https://fec-dev-api.app.cloud.gov/developers/)

**Comment by pkfec** [comment]
Deployed `test-npm-audit-fix` test branch to `dev` space. Tested `/candidates/` and `schedules/schedule_e` endpoints  on swagger. Results came back OK. No issues found on the browser console. 

CircleCI build:https://app.circleci.com/pipelines/github/fecgov/openFEC/1058/workflows/f1740774-6dcc-4b28-a508-23484204500d/jobs/3523


**endpoints:**
1. https://fec-dev-api.app.cloud.gov/v1/candidates/?per_page=20&page=1&sort_nulls_last=false&sort_null_only=false&sort_hide_null=false&sort=name
2. https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_e/?per_page=20&sort_nulls_last=false&sort_null_only=false&sort_hide_null=false&sort=-expenditure_date

**Review by pkfec — APPROVED** [review]
Changes looks good @lbeaufort

**Pull request merged**
