### PR TITLE
4764  Add index to ofec_totals_combined_mv #4764 for performance abou…

### LINKED ISSUE #4764: Add index to ofec_totals_combined_mv
Summary:
ofec_totals_combined_mv needs to tuned for cpu and long time 
Successfully run. Total query runtime: 12 secs 36 msec.
it is top 4 cpu usage sql (7.25%)
image

**Related work:**
https://github.com/fecgov/openFEC/issues/4774 Query logic improvement for ofec_totals_combined_mv

**Completion criteria:**
- [ ] Add a new index on the ofec_totals_combined_mv
   - There is missing index on   get_cycle(vsd.rpt_yr) AS **cycle**  or rpt_yr) at  MATERIALIZED VIEW public.ofec_totals_combined_mv.
   -  Suggestion:
   -  CREATE INDEX idx_ofec_totals_combined_mv_cmte_id_cycle
    ON public.ofec_totals_combined_mv USING btree
    (committee_id DESC NULLS LAST, cycle  DESC NULLS LAST) ;

- [ ] Add a migration file to reflect the change

image

Here is the sql
```SQL
SELECT   ofec_totals_pac_party_vw.idx AS ofec_totals_pac_party_vw_idx,   ofec_totals_pac_party_vw.committee_id AS   ofec_totals_pac_party_vw_committee_id, ofec_totals_pac_party_vw.cycle AS   ofec_totals_pac_party_vw_cycle, ofec_totals_pac_party_vw.offsets_to_operating_expenditures   AS ofec_totals_pac_party_vw_offsets_to_operating_expenditure_1,   ofec_totals_pac_party_vw.political_party_committee_contributions AS   ofec_totals_pac_party_vw_political_party_committee_contri_2,   ofec_totals_pac_party_vw.other_disbursements AS   ofec_totals_pac_party_vw_other_disbursements,   ofec_totals_pac_party_vw.other_political_committee_contributions AS   ofec_totals_pac_party_vw_other_political_committee_contri_3,   ofec_totals_pac_party_vw.individual_itemized_contributions AS ofec_totals_pac_party_vw_individual_itemized_contribution_4,   ofec_totals_pac_party_vw.individual_unitemized_contributions AS   ofec_totals_pac_party_vw_individual_unitemized_contributi_5,   ofec_totals_pac_party_vw.operating_expenditures AS   ofec_totals_pac_party_vw_operating_expenditures,   ofec_totals_pac_party_vw.disbursements AS   ofec_totals_pac_party_vw_disbursements,   ofec_totals_pac_party_vw.contributions AS   ofec_totals_pac_party_vw_contributions,   ofec_totals_pac_party_vw.contribution_refunds AS ofec_totals_pac_party_vw_contribution_refunds,   ofec_totals_pac_party_vw.individual_contributions AS   ofec_totals_pac_party_vw_individual_contributions,   ofec_totals_pac_party_vw.refunded_individual_contributions AS   ofec_totals_pac_party_vw_refunded_individual_contribution_6,   ofec_totals_pac_party_vw.refunded_other_political_committee_contributions AS   ofec_totals_pac_party_vw_refunded_other_political_committ_7,   ofec_totals_pac_party_vw.refunded_political_party_committee_contributions AS   ofec_totals_pac_party_vw_refunded_political_party_committ_8,   ofec_totals_pac_party_vw.receipts AS ofec_totals_pac_party_vw_receipts,   ofec_totals_pac_party_vw.coverage_start_date AS   ofec_totals_pac_party_vw_coverage_start_date,   ofec_totals_pac_party_vw.coverage_end_date AS ofec_totals_pac_party_vw_coverage_end_date,   ofec_totals_pac_party_vw.net_contributions AS   ofec_totals_pac_party_vw_net_contributions,   ofec_totals_pac_party_vw.net_operating_expenditures AS   ofec_totals_pac_party_vw_net_operating_expenditures,   ofec_totals_pac_party_vw.last_report_year AS   ofec_totals_pac_party_vw_last_report_year,   ofec_totals_pac_party_vw.last_report_type_full AS   ofec_totals_pac_party_vw_last_report_type_full,   ofec_totals_pac_party_vw.last_beginning_image_number AS   ofec_totals_pac_party_vw_last_beginning_image_number,   ofec_totals_pac_party_vw.last_cash_on_hand_end_period AS   ofec_totals_pac_party_vw_last_cash_on_hand_end_period,   ofec_totals_pac_party_vw.last_debts_owed_by_committee AS   ofec_totals_pac_party_vw_last_debts_owed_by_committee, ofec_totals_pac_party_vw.last_debts_owed_to_committee   AS ofec_totals_pac_party_vw_last_debts_owed_to_committee,   ofec_totals_pac_party_vw.committee_name AS   ofec_totals_pac_party_vw_committee_name,   ofec_totals_pac_party_vw.committee_type AS ofec_totals_pac_party_vw_committee_type,   ofec_totals_pac_party_vw.committee_designation AS   ofec_totals_pac_party_vw_committee_designation,   ofec_totals_pac_party_vw.committee_type_full AS   ofec_totals_pac_party_vw_committee_type_full,   ofec_totals_pac_party_vw.committee_designation_full AS ofec_totals_pac_party_vw_committee_designation_full,   ofec_totals_pac_party_vw.party_full AS ofec_totals_pac_party_vw_party_full,   ofec_totals_pac_party_vw.all_loans_received AS   ofec_totals_pac_party_vw_all_loans_received,   ofec_totals_pac_party_vw.allocated_federal_election_levin_share AS   ofec_totals_pac_party_vw_allocated_federal_election_levin_9,   ofec_totals_pac_party_vw.coordinated_expenditures_by_party_committee AS   ofec_totals_pac_party_vw_coordinated_expenditures_by_part_a,   ofec_totals_pac_party_vw.fed_candidate_committee_contributions AS   ofec_totals_pac_party_vw_fed_candidate_committee_contribu_b,   ofec_totals_pac_party_vw.fed_candidate_contribution_refunds AS   ofec_totals_pac_party_vw_fed_candidate_contribution_refun_c,   ofec_totals_pac_party_vw.fed_disbursements AS   ofec_totals_pac_party_vw_fed_disbursements,   ofec_totals_pac_party_vw.fed_election_activity AS   ofec_totals_pac_party_vw_fed_election_activity,   ofec_totals_pac_party_vw.fed_operating_expenditures AS   ofec_totals_pac_party_vw_fed_operating_expenditures,   ofec_totals_pac_party_vw.fed_receipts AS   ofec_totals_pac_party_vw_fed_receipts,   ofec_totals_pac_party_vw.independent_expenditures AS   ofec_totals_pac_party_vw_independent_expenditures,   ofec_totals_pac_party_vw.loan_repayments_made AS ofec_totals_pac_party_vw_loan_repayments_made,   ofec_totals_pac_party_vw.loan_repayments_received AS   ofec_totals_pac_party_vw_loan_repayments_received,   ofec_totals_pac_party_vw.loans_made AS ofec_totals_pac_party_vw_loans_made,   ofec_totals_pac_party_vw.non_allocated_fed_election_activity AS   ofec_totals_pac_party_vw_non_allocated_fed_election_activ_d,   ofec_totals_pac_party_vw.total_transfers AS   ofec_totals_pac_party_vw_total_transfers,   ofec_totals_pac_party_vw.other_fed_operating_expenditures AS   ofec_totals_pac_party_vw_other_fed_operating_expenditures,   ofec_totals_pac_party_vw.other_fed_receipts AS   ofec_totals_pac_party_vw_other_fed_receipts,   ofec_totals_pac_party_vw.shared_fed_activity AS   ofec_totals_pac_party_vw_shared_fed_activity, ofec_totals_pac_party_vw.shared_fed_activity_nonfed   AS ofec_totals_pac_party_vw_shared_fed_activity_nonfed,   ofec_totals_pac_party_vw.shared_fed_operating_expenditures AS   ofec_totals_pac_party_vw_shared_fed_operating_expenditure_e,   ofec_totals_pac_party_vw.shared_nonfed_operating_expenditures AS   ofec_totals_pac_party_vw_shared_nonfed_operating_expendit_f,   ofec_totals_pac_party_vw.transfers_from_affiliated_party AS   ofec_totals_pac_party_vw_transfers_from_affiliated_party,   ofec_totals_pac_party_vw.transfers_from_nonfed_account AS ofec_totals_pac_party_vw_transfers_from_nonfed_account,   ofec_totals_pac_party_vw.transfers_from_nonfed_levin AS   ofec_totals_pac_party_vw_transfers_from_nonfed_levin,   ofec_totals_pac_party_vw.transfers_to_affiliated_committee AS   ofec_totals_pac_party_vw_transfers_to_affiliated_committe_10,   ofec_totals_pac_party_vw.cash_on_hand_beginning_period AS   ofec_totals_pac_party_vw_cash_on_hand_beginning_period,   ofec_totals_pac_party_vw.federal_funds AS   ofec_totals_pac_party_vw_federal_funds, ofec_totals_pac_party_vw.loans_and_loan_repayments_received   AS ofec_totals_pac_party_vw_loans_and_loan_repayments_receiv_11,   ofec_totals_pac_party_vw.loans_and_loan_repayments_made AS   ofec_totals_pac_party_vw_loans_and_loan_repayments_made,   ofec_totals_pac_party_vw.exp_subject_limits AS   ofec_totals_pac_party_vw_exp_subject_limits,   ofec_totals_pac_party_vw.exp_prior_years_subject_limits AS   ofec_totals_pac_party_vw_exp_prior_years_subject_limits,   ofec_totals_pac_party_vw.total_exp_subject_limits AS   ofec_totals_pac_party_vw_total_exp_subject_limits,   ofec_totals_pac_party_vw.refunds_relating_convention_exp AS   ofec_totals_pac_party_vw_refunds_relating_convention_exp,   ofec_totals_pac_party_vw.itemized_refunds_relating_convention_exp AS   ofec_totals_pac_party_vw_itemized_refunds_relating_conven_12,   ofec_totals_pac_party_vw.unitemized_refunds_relating_convention_exp AS   ofec_totals_pac_party_vw_unitemized_refunds_relating_conv_13,   ofec_totals_pac_party_vw.other_refunds AS   ofec_totals_pac_party_vw_other_refunds, ofec_totals_pac_party_vw.itemized_other_refunds   AS ofec_totals_pac_party_vw_itemized_other_refunds,   ofec_totals_pac_party_vw.unitemized_other_refunds AS   ofec_totals_pac_party_vw_unitemized_other_refunds,   ofec_totals_pac_party_vw.itemized_other_income AS ofec_totals_pac_party_vw_itemized_other_income,   ofec_totals_pac_party_vw.unitemized_other_income AS   ofec_totals_pac_party_vw_unitemized_other_income,   ofec_totals_pac_party_vw.convention_exp AS   ofec_totals_pac_party_vw_convention_exp,   ofec_totals_pac_party_vw.itemized_convention_exp AS   ofec_totals_pac_party_vw_itemized_convention_exp,   ofec_totals_pac_party_vw.unitemized_convention_exp AS   ofec_totals_pac_party_vw_unitemized_convention_exp,   ofec_totals_pac_party_vw.itemized_other_disb AS   ofec_totals_pac_party_vw_itemized_other_disb,   ofec_totals_pac_party_vw.unitemized_other_disb AS   ofec_totals_pac_party_vw_unitemized_other_disb,   ofec_agg_coverage_date_mv_1.fec_election_yr AS   ofec_agg_coverage_date_mv_1_fec_election_yr, ofec_agg_coverage_date_mv_1.idx   AS ofec_agg_coverage_date_mv_1_idx, ofec_agg_coverage_date_mv_1.committee_id   AS ofec_agg_coverage_date_mv_1_committee_id,   ofec_agg_coverage_date_mv_1.transaction_coverage_date AS   ofec_agg_coverage_date_mv_1_transaction_coverage_date      FROM ofec_totals_pac_party_vw LEFT OUTER JOIN ofec_agg_coverage_date_mv AS   ofec_agg_coverage_date_mv_1 ON ofec_totals_pac_party_vw.committee_id =   ofec_agg_coverage_date_mv_1.committee_id AND ofec_totals_pac_party_vw.cycle =   ofec_agg_coverage_date_mv_1.fec_election_yr      
WHERE ofec_totals_pac_party_vw.committee_id = $1 AND   ofec_totals_pac_party_vw.cycle IN ($2) AND ofec_totals_pac_party_vw.cycle IS   NOT NULL 
ORDER BY ofec_totals_pac_party_vw.cycle DESC       
LIMIT $3 OFFSET $4
```
--
note: ofec_totals_pac_party_vw  is using ... .. to the root  public.ofec_totals_combined_mv

### PR DESCRIPTION
**Pull request by dzhang-fec**
## Summary (required)

- Resolves #4764 

Add index to ofec_totals_combined_mv #4764 for performance about 3 times faster 
by CREATE INDEX idx_ofec_totals_combined_mv_cmte_id_cycle ON ofec_totals_combined_mv

## How to test the changes locally
-Please review #4764 
 execution time and execution plan

## Impacted areas of the application
  It will be about 3  times faster ON ofec_totals_combined_mv queries (very often)

-

### CODE REVIEW

**Comment by hcaofec** [comment]
Because the index is already added in database, It will throw error when merging this PR.  Maybe add "if exist" to catch the exception?  @dzhang-fec

**Review by fecjjeng — CHANGES_REQUESTED** [review]
As @hcaofec mentioned, since this index had already been created in the database, running this migration file will resulted in error.  
Please either add if exists or remove the index from the database. 
Also please provide method for local test in the PR.

**Comment by fecjjeng** [comment]
@dzhang-fec We usually pre-build indexes in non-peak hour when the indexes creation will take long time (for example, on the 20+ partition tables of the disclosure.fec_fec_fitem_sched_a/b), and migration file in that case need to use special syntax so it won't cause error.  For small table/MV like this one, in theory there is no need to pre-build.  Having said that, since this MV is heavily used during peak hour, it is a good idea to pre-build the index during non-peak hour, but please remember to add if not exists clause so it will not cause error during merging.

**Comment by dzhang-fec** [comment]
@hcaofec @fecjjeng Thanks a lot for your review. I have updated. Please review again when you get time. Thanks

**Comment by fecjjeng** [comment]
To test changes locally:
I had run the following steps.
- download branch to local machine, run flyway migration, migration file executed successfully.
- log into local cfdm_test database, 
select * from pg_indexes where indexname = 'idx_ofec_totals_combined_mv_cmte_id_cycle';
shows index created successfully.
-- to mimic the situation in aurora database where the index had been created, 
delete from flyway_schema_history where version = '0222';
-- run flyway migrate again.  
migration file executed successfully.

**Comment by fecjjeng** [comment]
@dzhang-fec 
I had run the test as described above to test the changes locally.  
Next time please provide method for local test in the PR in the section "How to test the changes locally"

**Review by fecjjeng — APPROVED** [review]
Test run successfully.  Approved the PR.

**Review by hcaofec — APPROVED** [review]
Looks good.

**Pull request merged**
