### PR TITLE
Fix schedule-b efile download multi same rows issue

### PR DESCRIPTION
**Pull request by fec-jli**
## Summary (required)
Schedule B efiling export downloading same row 100,000 times

- Resolves [#4825 ](https://github.com/fecgov/openFEC/issues/4825)

### Required reviewers
two backend developers

## Impacted areas of the application
schems.py

General components of the application that this PR will affect:
disbursement--raw data--download 
  
## How to test
1)checkout branch
2)two optionals to test
a)deploy to stage space, test disbursement--raw data--download 
b)follow the wiki to setup Redis, Celery-worker on local to test disbursement--raw data--download.
[Set up Redis, Celery on local and test the task](https://github.com/fecgov/openFEC/wiki/Set-up-Redis,--Celery-on-local-and-test-the-tasks)

3)ex url like this: you can filter some data to export
https://stage.fec.gov/data/disbursements/?data_type=efiling&committee_id=C00702944

### CODE REVIEW

**Comment by pkfec** [comment]
Deployed changes to stage and tested download for C00075820. Was able to download and view 43 results for C00075820

https://stage.fec.gov/data/disbursements/?data_type=efiling&committee_id=C00075820&disbursement_description=HQ+ACCT+-+CONTRIBUTION+REFUND

**Review by pkfec — APPROVED** [review]
@fec-jli Great job on finding this tricky bug. Changes look good.

**Review by lbeaufort — COMMENTED** [review]
Thanks for your hard work in identifying this tricky bug, @fec-jli! Is this an opportunity to add more test coverage?

**Comment by fec-jli** [comment]
This PR change will merge to release branch. close.
Ref PR:  [https://github.com/fecgov/openFEC/pull/4884](https://github.com/fecgov/openFEC/pull/4884)

**Pull request closed without merging**
