### PR TITLE
Feature/5996 add MUR citations

### LINKED ISSUE #5996: Add MUR citations to the legal/citations endpoint
### What we’re after

 We should add MUR citations to the legal/citations endpoint. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)

- [ ] https://github.com/fecgov/openFEC/issues/5979

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [ ] MUR citations can be found in the citations endpoint

### PR DESCRIPTION
**Pull request by tmpayton**
## Summary (required)

- Resolves #5996 

This ticket loads the mur citations into the `legal/citations` endpoint

## Impacted areas of the application

- MUR load 
- Archived MUR load

## How to test

- Checkout this branch
- Start elasticsearh
- Create case_index: `python cli.py create_index case_index`
- load current murs: `python cli.py load_current_murs` you can stop this early - citations are loaded first 
- `flask run`

Test citations endpoint and doc_type filter: 
http://127.0.0.1:5000/v1/legal/citation/statute/10
http://127.0.0.1:5000/v1/legal/citation/regulation/100.13
http://127.0.0.1:5000/v1/legal/citation/regulation/1/?doc_type=murs
http://127.0.0.1:5000/v1/legal/citation/statute/9/?doc_type=murs
http://127.0.0.1:5000/v1/legal/citation/statute/9/?doc_type=advisory_opinions (no murs show)

Check MUR disposition citations against prod:

https://api.open.fec.gov/v1/legal/search/?type=murs&case_no=8261&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/legal/search/?type=murs&case_no=8261

https://api.open.fec.gov/v1/legal/search/?type=murs&case_no=8201&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/legal/search/?type=murs&case_no=8201

https://api.open.fec.gov/v1/legal/search/?type=murs&case_no=8062&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/legal/search/?type=murs&case_no=8062

https://api.open.fec.gov/v1/legal/search/?type=murs&case_no=8059&api_key=DEMO_KEY
http://127.0.0.1:5000/v1/legal/search/?type=murs&case_no=8059

Testing on dev: compare mur citations to ensure there are no changes: 

https://www.fec.gov/data/legal/matter-under-review/8261/
https://dev.fec.gov/data/legal/matter-under-review/8261/

https://www.fec.gov/data/legal/matter-under-review/8208/
https://dev.fec.gov/data/legal/matter-under-review/8208/

https://www.fec.gov/data/legal/matter-under-review/8059/
https://dev.fec.gov/data/legal/matter-under-review/8059/

https://www.fec.gov/data/legal/matter-under-review/7912/
https://dev.fec.gov/data/legal/matter-under-review/7912/

### CODE REVIEW

**Comment by patphongs** [comment]
@tmpayton Let's remove the archived MURs from the MUR citation filters for now. It's our understanding that the data for archived MURs citations could be messy or missing. I will create a separate ticket to tackle this work to clean it up.

**Comment by tmpayton** [comment]
I removed the archive mur changes!

**Review by cnlucas — APPROVED** [review]
This is working great for me, excellent job @tmpayton

**Review by pkfec — APPROVED** [review]
Changes work as expected, thanks @tmpayton

**Pull request merged**
