### PR TITLE
[MERGE WITH GITFLOW] 5871- Hotfix/5871 fix broken links

### LINKED ISSUE #5871: Broken links in README.md and  Typo in api documentation
### What we’re after

- Links in the  [api umbrella](https://github.com/fecgov/openFEC#api-umbrella ) and [caching](https://github.com/fecgov/openFEC#caching) sections of  `README.md` redirect to a "sports betting blog" webpage, (https://apiumbrella.io/)

- Umbrella link should be changed to  `https://api.data.gov/` 

- Typo in api documentation (swagger docs) "P00000002 Democrasts."  Someone sent us an email to APIinfo about the typo.  [https://api.open.fec.gov/developers/#/presidential/get_v1_presidential_contributions_by_state_](https://api.open.fec.gov/developers/#/presidential/get_v1_presidential_contributions_by_state_)

### Completion criteria

- [ ] Links in the  [api umbrella](https://github.com/fecgov/openFEC#api-umbrella ) and [caching](https://github.com/fecgov/openFEC#caching) sections of  README.md go to to `https://api.data.gov/`
- [ ] Typo in [https://api.open.fec.gov/developers/#/presidential/get_v1_presidential_contributions_by_state_](https://api.open.fec.gov/developers/#/presidential/get_v1_presidential_contributions_by_state_) is corrected
<hr>

api_umbrella_sports

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary (required)

- Resolves #5871 

Switches broken link and removes typo

### Required reviewers

1 dev

## Impacted areas of the application

General components of the application that this PR will affect:

- API readme and docs

## How to test

- Go to the link
- pull this PR
- flask run

### CODE REVIEW

**Review by tmpayton — CHANGES_REQUESTED** [review]
I am still getting the sport betting link when I click the API umbrella link under caching. The other changes look good, Awesome job!

**Comment by cnlucas** [comment]
> I am still getting the sport betting link when I click the API umbrella link under caching. The other changes look good, Awesome job!

Thank you for catching this!

**Review by tmpayton — APPROVED** [review]
Looks good! Thank you for creating this hotfix so quickly!

**Review by fec-jli — APPROVED** [review]
It looks good. Thanks

**Pull request merged**
