### PR TITLE
Add committee_id validation

### LINKED ISSUE #5603: Add committee_id validation
### What we’re after
When api user pass invalid committee_id, will throw 422 error, save to call api.
This involves many endpoints that include committee_id as filter.

### Action item(s)
- [x] Add committee_id validation function in args.py and modify committee_id in args.py
- [x] Test all endpoints
- [x] Modify automated test cases 

### Completion criteria
- [x] All endpoints with committee_id filter will have committee_id validation.

### PR DESCRIPTION
**Pull request by tmpayton**
## Summary (required)

- Resolves #5603 

This ticket adds validation to the committee_id field by adding a custom field in args.py and adding validation to committee_id in paths (for instance: v1/committee/C00429613/filings/).  It checks that the length is exactly 9, that it begins with a capital 'C', and that the characters after 'C' are digits. 

## Impacted areas of the application

General components of the application that this PR will affect:

-  all committee_id fields 
- all automated tests that use committee_id 
- args.py

## How to test

- checkout this branch 
- flask run 
- test all endpoints that use committee_id. I will include a list of endpoints and test urls in the comments.

### CODE REVIEW

**Comment by tmpayton** [comment]
Endpoints that use committee_id: 

[/v1/candidate/{candidate_id}/committees/history/](http://127.0.0.1:5000/developers/#/committee/get_v1_candidate__candidate_id__committees_history_)
[/v1/candidate/{candidate_id}/committees/history/{cycle}/](http://127.0.0.1:5000/developers/#/committee/get_v1_candidate__candidate_id__committees_history__cycle__)
[/v1/committees/](http://127.0.0.1:5000/developers/#/committee/get_v1_committees_)
[/v1/reports/{entity_type}/](http://127.0.0.1:5000/developers/#/financial/get_v1_reports__entity_type__)
[/v1/totals/inaugural_committees/by_contributor/](http://127.0.0.1:5000/developers/#/financial/get_v1_totals_inaugural_committees_by_contributor_)
[/v1/schedules/schedule_a/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_)
[/v1/schedules/schedule_a/by_employer/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_by_employer_)
[/v1/schedules/schedule_a/by_occupation/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_by_occupation_)
[/v1/schedules/schedule_a/by_size/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_by_size_)
[/v1/schedules/schedule_a/by_state/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_by_state_)
[/v1/schedules/schedule_a/by_zip/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_by_zip_)
[/v1/schedules/schedule_a/efile/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a_efile_)
[/v1/schedules/schedule_a/{sub_id}/](http://127.0.0.1:5000/developers/#/receipts/get_v1_schedules_schedule_a__sub_id__)
[/v1/schedules/schedule_b/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_b_)
[/v1/schedules/schedule_b/by_purpose/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_b_by_purpose_)
[/v1/schedules/schedule_b/by_recipient/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_b_by_recipient_)
[/v1/schedules/schedule_b/by_recipient_id/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_b_by_recipient_id_)
[/v1/schedules/schedule_b/efile/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_b_efile_)
[/v1/schedules/schedule_b/{sub_id}/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_b__sub_id__)
[/v1/schedules/schedule_h4/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_h4_)
[/v1/schedules/schedule_h4/efile/](http://127.0.0.1:5000/developers/#/disbursements/get_v1_schedules_schedule_h4_efile_)
[/v1/schedules/schedule_c/](http://127.0.0.1:5000/developers/#/loans/get_v1_schedules_schedule_c_)
[/v1/schedules/schedule_d/](http://127.0.0.1:5000/developers/#/debts/get_v1_schedules_schedule_d_)
[/v1/schedules/schedule_e/](http://127.0.0.1:5000/developers/#/independent%20expenditures/get_v1_schedules_schedule_e_)
[/v1/schedules/schedule_e/efile/](http://127.0.0.1:5000/developers/#/independent%20expenditures/get_v1_schedules_schedule_e_efile_)
[/v1/schedules/schedule_f/](http://127.0.0.1:5000/developers/#/party-coordinated%20expenditures/get_v1_schedules_schedule_f_)
[/v1/communication_costs/](http://127.0.0.1:5000/developers/#/communication%20cost/get_v1_communication_costs_)
[/v1/communication_costs/aggregates/](http://127.0.0.1:5000/developers/#/communication%20cost/get_v1_communication_costs_aggregates_)
[/v1/electioneering/](http://127.0.0.1:5000/developers/#/electioneering/get_v1_electioneering_)
[/v1/electioneering/aggregates/](http://127.0.0.1:5000/developers/#/electioneering/get_v1_electioneering_aggregates_)
[/v1/rad-analyst/](http://127.0.0.1:5000/developers/#/filer%20resources/get_v1_rad_analyst_)
[/v1/efile/filings/](http://127.0.0.1:5000/developers/#/efiling/get_v1_efile_filings_)
[/v1/efile/reports/house-senate/](http://127.0.0.1:5000/developers/#/efiling/get_v1_efile_reports_house_senate_)
[/v1/efile/reports/pac-party/](http://127.0.0.1:5000/developers/#/efiling/get_v1_efile_reports_pac_party_)
[/v1/efile/reports/presidential/](http://127.0.0.1:5000/developers/#/efiling/get_v1_efile_reports_presidential_)
[/v1/audit-case/](http://127.0.0.1:5000/developers/#/audit/get_v1_audit_case_)
[/v1/filings/](http://127.0.0.1:5000/developers/#/filings/get_v1_filings_)

**Comment by tmpayton** [comment]
More endpoints and sample URLs: 

/v1/reports/{entity_type}/

http://127.0.0.1:5000/v1/reports/presidential/?page=1&per_page=20&committee_id=c00838375&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/reports/presidential/?page=1&per_page=20&committee_id=C00838375&committee_id=c00578245&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/reports/presidential/?page=1&per_page=20&committee_id=C00838375&committee_id=c0057824&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/reports/presidential/?page=1&per_page=20&committee_id=C00838375&committee_id=M00578245&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/reports/presidential/?page=1&per_page=20&committee_id=C00838375&committee_id=C0T578245&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/schedules/schedule_e/by_candidate/

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=1984&office=president&election_full=true&committee_id=C00000000&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=1984&office=president&election_full=true&committee_id=c00000000&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=1984&office=president&election_full=true&committee_id=c00000000b&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=1984&office=president&election_full=true&committee_id=A00000000&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=1984&office=president&election_full=true&committee_id=Ch0000000&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=2016&office=president&election_full=true&committee_id=C00626689&committee_id=C000009352&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=2016&office=president&election_full=true&committee_id=C00626689&committee_id=C000a0935&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/schedules/schedule_e/by_candidate/?page=1&per_page=20&cycle=2016&office=president&election_full=true&committee_id=C00626689&committee_id=c00000935&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false


/v1/schedules/schedule_a/

http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=C00157404&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false

http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=c00157404&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false

http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=C00157404&committee_id=C00436980&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false

http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=C00157404&committee_id=c00436980&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false

http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=C00157404&committee_id=c0043698000&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false

http://127.0.0.1:5000/v1/schedules/schedule_a/?committee_id=C00157404&committee_id=c0u436980&per_page=20&sort=-contribution_receipt_date&sort_hide_null=false&sort_null_only=false


/v1/committee/{committee_id}/filings/

http://127.0.0.1:5000/v1/committee/C00429613/filings/?page=1&per_page=20&sort=-receipt_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c00429613/filings/?page=1&per_page=20&sort=-receipt_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0042961300/filings/?page=1&per_page=20&sort=-receipt_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/ct0429613/filings/?page=1&per_page=20&sort=-receipt_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/T00429613/filings/?page=1&per_page=20&sort=-receipt_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/committee/{committee_id}/candidates/history/{cycle}/

http://127.0.0.1:5000/v1/committee/c00429613/candidates/history/2008/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/C00429613/candidates/history/2008/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c004296/candidates/history/2008/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c00-29613/candidates/history/2008/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/P00429613/candidates/history/2008/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/committee/{committee_id}/candidates/history/

http://127.0.0.1:5000/v1/committee/c00429613/candidates/history/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0042961300/candidates/history/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/u00429613/candidates/history/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0b429613/candidates/history/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/committee/{committee_id}/candidates/

http://127.0.0.1:5000/v1/committee/c00429613/candidates/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0042961300/candidates/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c004A9613/candidates/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/b00429613/candidates/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c004a9613/candidates/history/?page=1&per_page=20&election_full=true&sort=-two_year_period&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false


/v1/committee/{committee_id}/totals/

http://127.0.0.1:5000/v1/committee/c00163121/totals/?page=1&per_page=20&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0016312/totals/?page=1&per_page=20&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0016P121/totals/?page=1&per_page=20&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/o00163121/totals/?page=1&per_page=20&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/committee/{committee_id}/

http://127.0.0.1:5000/v1/committee/C00462390/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c00462390/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0046239/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/a00462390/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c00462H90/?page=1&per_page=20&sort=name&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/committee/{committee_id}/history/

http://127.0.0.1:5000/v1/committee/C00684373/history/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c00684373/history/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0068437300/history/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/A00684373/history/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/C006AA373/history/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

/v1/committee/{committee_id}/history/{cycle}/

http://127.0.0.1:5000/v1/committee/c00684373/history/2022/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/C0068437/history/2022/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/C006QE373/history/2022/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/m00684373/history/2022/?page=1&per_page=20&election_full=true&sort=-cycle&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false


/v1/committee/{committee_id}/reports/

http://127.0.0.1:5000/v1/committee/c00223743/reports/?page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0022374G/reports/?page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/b00223743/reports/?page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

http://127.0.0.1:5000/v1/committee/c0022374300/reports/?page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

**Comment by fec-jli** [comment]
We need add committee_id validation in the following view Classes (endpoints)?

1)'/totals/<string:entity_type>/'
(total.TotalsByEntityTypeView)

2)'/totals/inaugural_committees/by_contributor/'
(total.InauguralDonationsView) 

3)'/efile/reports/house-senate/'
reports.EFilingHouseSenateSummaryView


4)in exceptions.py message: should say committee_id, not committee_ids

**Review by fec-jli — APPROVED** [review]
Test on local api and cms. work as expected. Great Job. Thanks

**Review by cnlucas — APPROVED** [review]
Great job, @tmpayton really excellent work!

**Review by pkfec — APPROVED** [review]
Adding validation to committee_id is very challenging and humongous task you executed it very efficiently. Thanks @tmpayton

**Pull request merged**
