### PR TITLE
update node v10.16.0

### LINKED ISSUE #4070: review config.yml and decide if necessary to upgrade npm/node
### Summary

`npm` and `node` build / deploy versions appear to be older than perhaps those local versions in use by the team. We may want to upgrade.

```
      - run:
          name: Install node dependencies
          command: |
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
            echo ". ~/.nvm/nvm.sh" >> $BASH_ENV
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
            nvm install 8.9.1
            nvm use 8.9.1
            nvm alias default 8.9.1
            npm install -g npm swagger-tools
            npm install
            npm run build
```

### Completion criteria
- [x] review `config.ym`
- [x] decide on modifying with other versions of npm (5.5.1) / node (8.9.1)

### PR DESCRIPTION
**Pull request by pkfec**
API is on `node v8.9.1` is no longer maintained and its support ended in JAN 2020.
In API, I have updated node to `v10.16.0` which is LTS version and its good thru APRIL 2021.

- Resolves #4070 

_Include a summary of proposed changes._

1. In circleci/config.yml file update node version

## How to test the changes locally

- Steps to update `node` and `npm` on local development environment:

1. Activate python virtual environment
2. List all the available node version that are already installed in your machine : `nvm ls`
3. Alias new version to default : `nvm alias default v10.16.0`
4. Use new version:  `nvm use default`
5. Upgrade npm:  `npm install -g npm`
6. Check node version: `node -v`
7. Check npm version : `npm -v` 
8. **At this point your node and npm should be : v10.16.0 & v6.13.7**
9. Remove node_modules/ from openFEC repo
10. clear cache : `npm cache clear`
10. Install node modules: `npm install`
11. Install all the python pkgs: `npm run build`
12. Install requirement.txt and requirement-dev.txt
13. Runserver :` ./manage.py runserver`
14. clear browsers cache
15. Launch API swagger doc and test endpoints

## Impacted areas of the application
List general components of the application that this PR will affect:

-  swagger-tools
- swagger docs

### CODE REVIEW

**Comment by lbeaufort** [comment]
Also, should the node version in `package.json` match the version in the Circle config file?

**Comment by pkfec** [comment]
> @pkfec it looks like this branch includes migration files - should those be part of this PR?

This is so weird. I dont know how this migration file ended up in this PR branch. Thanks for flagging this.
I will fix this PR

**Comment by pkfec** [comment]
> Also, should the node version in `package.json` match the version in the Circle config file?

good catch @lbeaufort . I forgot to push the changes up.

**Comment by pkfec** [comment]
This branch has some unintended migration files that are not part of the change. I have submitted a new PR and the changes can be tracked in the new PR https://github.com/fecgov/openFEC/pull/4226

closing this PR.

**Pull request closed without merging**
