### PR TITLE
Feature/6009 add case tests

### LINKED ISSUE #6009: Add case document tests to legal/search endpoint
### What we’re after

As an action item for the postmortem on 10/7, we should increase logging and test coverage for our legal search endpoint. Specifically we should have at least one test that will fail if any of the documents types are not returning which includes both current and archived murs

[Codecov run of legal.py](https://app.codecov.io/gh/fecgov/openFEC/blob/develop/webservices%2Fresources%2Flegal.py)
### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)

- [ ]

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)

- [ ] [Our test coverage](https://app.codecov.io/gh/fecgov/openFEC/blob/develop/webservices%2Fresources%2Flegal.py) has improved for legal.py
- [ ] A test has been included that would have caught the missing archived murs before deployment

### Completion criteria

(What does the end state look like - as long as this task(s) is done, this work is complete)

- [ ]

### References/resources/technical considerations

(Is there sample code or a screenshot you can include to highlight a particular issue? Here is where you reinforce why this work is important)

### PR DESCRIPTION
**Pull request by tmpayton**
## Summary (required)

- Resolves #6009 

This ticket adds integration testing with Elasticsearch to test all case filters. I will make separate PRs for AOs, statutes, and the other legal endpoints. 

## Impacted areas of the application

General components of the application that this PR will affect:

- circleci pipeline
- pytest

## How to test

- checkout this branch
- start elasticsearch in new terminal 
- run `pytest` in another terminal
- to see output from any individual test uncomment the logging statements and run ` pytest tests/integration/test_cases_elasticsearch.py -s` 

Note: running locally will clear out your elasticsearch environment 
- look at codecov to see increase in coverage https://app.codecov.io/gh/fecgov/openFEC/blob/feature%2F6009-add-case-tests/webservices%2Fresources%2Flegal.py

### CODE REVIEW

**Comment by fec-jli** [comment]
Great work !!!
1)We need to update the README file to include instructions for testing the Elasticsearch part locally. such as: start Elasticsearch server locally before run `pytest`
2)change file name `legal_test_data.py` to `test_legal_data.py` (naming convention)

**Comment by tmpayton** [comment]
> Great work !!! 1)We need to update the README file to include instructions for testing the Elasticsearch part locally. such as: start Elasticsearch server locally before run `pytest` 2)change file name `legal_test_data.py` to `test_legal_data.py` (naming convention)

Thank you for the review @fec-jli, I made the changes you requested!

**Review by pkfec — APPROVED** [review]
@tmpayton Thanks for setting up the es framework in circleci to run the actual tests. Excellent work

**Review by cnlucas — APPROVED** [review]
Really great work @tmpayton!

**Review by fec-jli — APPROVED** [review]
great work!

**Pull request merged**
