### PR TITLE
Create model CommitteeHistoryProfile and Refactor CommitteeHistory join 

### PR DESCRIPTION
**Pull request by fec-jli**
## Summary (required)
In order to improve the api performance, this PR will 
1)Remove join `JFCCommittee` model from `CommitteeHistory` model that are used by these endpoints:
/schedules/schedule_a/
/schedules/schedule_b/
/schedules/schedule_c/
/schedules/schedule_d/
/schedules/schedule_e/
/schedules/schedule_f/
/schedules/schedule_h4/
/reports/presidential/
/reports/house-senate/
/reports/pac-party/
/filings/
/totals/
....

2)Create new model `CommitteeHistoryProfile` join `JFCCommittee` model that are used by these 4 endpoints: (resource class: CommitteeHistoryProfileView)
/committee/<string:committee_id>/history/
/committee/<string:committee_id>/history/<int:cycle>/
/candidate/<string:candidate_id>/committees/history/
/candidate/<string:candidate_id>/committees/history/<int:cycle>/

- Resolves [https://github.com/fecgov/openFEC/issues/5270](https://github.com/fecgov/openFEC/issues/5270)
- partial of #5267

3)Reference Google Drive doc: [Endpoint Information](https://docs.google.com/spreadsheets/d/1AkQjXA2XMQfxlRyinSY0uynhf2ZRMh7l_BTWdJgHzXY/edit#gid=700639845)
[Committee Model & endpoints relation](https://docs.google.com/drawings/d/1KEBYJiscDxoLQbwqKCMV89KNII-9itUuF1poMNnRDZ8/edit)

### Required reviewers
2 developers
John is must on front-end.

## Impacted areas of the application
committee_model_relation

General components of the application that this PR will affect:
Most of endpoints except endpoints under tags: audit, legal, dates, presidential and filer resources.

## How to test
1)checkout branch
2)pytest
3)test endpoints on local or dev space and compare with prod api.
http://127.0.0.1:5000/v1/
https://fec-dev-api.app.cloud.gov/v1/
https://api.open.fec.gov/v1/

4)sample urls (committee object without join JFCcommittee)
**/schedules/schedule_a/**
(search `contributor` and `committee`, you will see two sub-object)
http://127.0.0.1:5000/v1/schedules/schedule_a/?two_year_transaction_period=2022&sort_hide_null=false&sort_null_only=false&sort=-contribution_receipt_date&per_page=20&committee_id=C00750166

https://api.open.fec.gov/v1/schedules/schedule_a/?two_year_transaction_period=2022&sort_hide_null=false&sort_null_only=false&sort=-contribution_receipt_date&per_page=20&committee_id=C00750166&api_key=DEMO_KEY
(jfc_committee sub-object inside `contributor` and `committee`)

**/schedules/schedule_b/**
(search `recipient_committee` and `committee`, you will see two sub-object)

https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_b/?two_year_transaction_period=2022&committee_id=C00750166&sort_null_only=false&sort=-disbursement_date&sort_hide_null=false&per_page=20

http://127.0.0.1:5000/v1/schedules/schedule_b/?two_year_transaction_period=2022&committee_id=C00750166&sort_null_only=false&sort=-disbursement_date&sort_hide_null=false&per_page=20

https://api.open.fec.gov/v1/schedules/schedule_b/?two_year_transaction_period=2022&committee_id=C00750166&sort_null_only=false&sort=-disbursement_date&sort_hide_null=false&per_page=20&api_key=DEMO_KEY
(jfc_committee sub-object inside `recipient_committee` and `committee`)

**/schedules/schedule_c/**
http://127.0.0.1:5000/v1/schedules/schedule_c/?sort_nulls_last=true&page=1&sort_null_only=false&sort_hide_null=false&sort=-incurred_date&per_page=20

https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_c/?sort_nulls_last=true&page=1&sort_null_only=false&sort_hide_null=false&sort=-incurred_date&per_page=20

https://api.open.fec.gov/v1/schedules/schedule_c/?sort_nulls_last=true&page=1&sort_null_only=false&sort_hide_null=false&sort=-incurred_date&per_page=20&api_key=DEMO_KEY

**/schedules/schedule_d/**
http://127.0.0.1:5000/v1/schedules/schedule_d/?sort_nulls_last=false&page=1&sort_null_only=false&sort=load_date&sort_hide_null=false&per_page=20

https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_d/?sort_nulls_last=false&page=1&sort_null_only=false&sort=load_date&sort_hide_null=false&per_page=20

https://api.open.fec.gov/v1/schedules/schedule_d/?sort_nulls_last=false&page=1&sort_null_only=false&sort=load_date&sort_hide_null=false&per_page=20&api_key=DEMO_KEY

**/schedules/schedule_e/**
http://127.0.0.1:5000/v1/schedules/schedule_e/?sort_nulls_last=false&most_recent=true&committee_id=C00331454&sort_null_only=false&sort=-expenditure_date&sort_hide_null=false&per_page=20

https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_e/?sort_nulls_last=false&most_recent=true&committee_id=C00331454&sort_null_only=false&sort=-expenditure_date&sort_hide_null=false&per_page=20

https://api.open.fec.gov/v1/schedules/schedule_e/?sort_nulls_last=false&most_recent=true&committee_id=C00331454&sort_null_only=false&sort=-expenditure_date&sort_hide_null=false&per_page=20&api_key=DEMO_KEY

**/schedules/schedule_f/**
http://127.0.0.1:5000/v1/schedules/schedule_f/?sort_nulls_last=false&sort_null_only=false&page=1&per_page=20&sort_hide_null=false&sort=expenditure_date

https://fec-dev-api.app.cloud.gov/v1/schedules/schedule_f/?sort_nulls_last=false&sort_null_only=false&page=1&per_page=20&sort_hide_null=false&sort=expenditure_date

https://api.open.fec.gov/v1/schedules/schedule_f/?sort_nulls_last=false&sort_null_only=false&page=1&per_page=20&sort_hide_null=false&sort=expenditure_date&api_key=DEMO_KEY

**/schedules/schedule_h4/**

**/reports/:**
http://127.0.0.1:5000/v1/reports/pac-party/?per_page=20&committee_id=C00750166&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&sort=-coverage_end_date&page=1

http://127.0.0.1:5000/v1/reports/house-senate/?per_page=20&committee_id=C00715722&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&sort=-coverage_end_date&page=1

http://127.0.0.1:5000/v1/reports/presidential/?per_page=20&committee_id=C00703975&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&sort=-coverage_end_date&page=1

(exclude `committee` object output, but still join JFCCommittee)
https://api.open.fec.gov/v1/reports/pac-party/?per_page=20&committee_id=C00750166&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&sort=-coverage_end_date&page=1&api_key=DEMO_KEY

**/filings/**
http://127.0.0.1:5000/v1/filings/?per_page=20&committee_id=C00750166&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&sort=-receipt_date&page=1

http://127.0.0.1:5000/v1/committee/C00750166/filings/?per_page=20&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false&sort=-receipt_date&page=1

**Aggregates**
http://127.0.0.1:5000/v1/schedules/schedule_a/by_employer/?per_page=20&sort_null_only=false&committee_id=C00750166&sort_nulls_last=false&sort_hide_null=false&page=1

http://127.0.0.1:5000/v1/schedules/schedule_b/by_recipient/?per_page=20&sort_null_only=false&committee_id=C00750166&sort_nulls_last=false&sort_hide_null=false&page=1

**Totals**
http://127.0.0.1:5000/v1/totals/pac-party/?sort_null_only=false&sort_nulls_last=false&per_page=20&committee_id=C00750166&sort=-cycle&sort_hide_null=false&page=1

http://127.0.0.1:5000/v1/committee/C00750166/totals/?sort=-cycle&per_page=20&sort_nulls_last=false&page=1&sort_null_only=false&sort_hide_null=false

The following 4 endpoints should join JFCCommittee and return jfc_committee object.
**/committee/<string:committee_id>/history/**
(return 10 rows in jfc_committee)
http://127.0.0.1:5000/v1/committee/C00750166/history/?sort_null_only=false&per_page=20&sort=-cycle&sort_nulls_last=false&election_full=true&sort_hide_null=false&page=1

(return empty[ ],  has 8 rows in fec_form_1s_vw and join_cmte_id = null)
http://127.0.0.1:5000/v1/committee/C00433615/history/?sort_null_only=false&per_page=20&sort=-cycle&sort_nulls_last=false&election_full=true&sort_hide_null=false&page=1

(on prod, return 8 empty{null } )
https://api.open.fec.gov/v1/committee/C00433615/history/?sort_null_only=false&per_page=20&sort=-cycle&sort_nulls_last=false&election_full=true&sort_hide_null=false&page=1&api_key=DEMO_KEY

(return empty[ ], no record in fec_form_1s_vw)
http://127.0.0.1:5000/v1/committee/C00827659/history/?sort_null_only=false&per_page=20&sort=-cycle&sort_nulls_last=false&election_full=true&sort_hide_null=false&page=1

**/committee/<string:committee_id>/history/<int:cycle>/**
https://fec-dev-api.app.cloud.gov/v1/committee/C00750166/history/2022/?sort_nulls_last=false&page=1&election_full=true&sort_hide_null=false&sort=-cycle&sort_null_only=false&per_page=20

**/candidate/<string:candidate_id>/committees/history/**
https://fec-dev-api.app.cloud.gov/v1/candidate/H2IL20042/committees/history/?sort_nulls_last=false&page=1&election_full=true&sort_hide_null=false&sort=-cycle&sort_null_only=false&per_page=20

**/candidate/<string:candidate_id>/committees/history/<int:cycle>/**
https://fec-dev-api.app.cloud.gov/v1/candidate/H2IL20042/committees/history/2020/?sort_nulls_last=false&page=1&election_full=true&sort_hide_null=false&sort=-cycle&sort_null_only=false&per_page=20

### CODE REVIEW

**Review by hcaofec — APPROVED** [review]
Great work!

**Review by cnlucas — APPROVED** [review]
Works for me, great job! Fingers crossed this helps with the 502's.  Could you  put in a ticket for the follow-up work you mentioned? Removing unnecessary portions from committee history and candidate?

**Review by pkfec — APPROVED** [review]
Thanks for refactoring API endpoints and have JFC info show up on the required committee/candidate history* endpoints. Great work @hcaofec @fec-jli!

**Review by johnnyporkchops — APPROVED** [review]
Tested profile pages, looks good!

**Pull request merged**
