### PR TITLE
[WIP] Feature/switch to simple query string

### LINKED ISSUE #5830: [Research] /legal/search endpoint: Respondents need capability for exact string match
### What we’re after

Currently the `respondents[ ]` field searches any word that matches. We want to add the ability to add exact string match in quotes for respondent as well. This is so results can be reduced, especially for common respondent names.

Ex: The search term "Salazar for Congress" currently returns many results because there are common respondent names with `for congress` in it. Limiting it to exactly that string would help narrow down the results.

**Action items:**
- [x] MURs
- [x] ADRs
- [ ] Create future work ticket to consider how this can be applied for admin fines
 This is not a hard change to make, but we need PM/design approval to search by name for AF's

https://api.open.fec.gov/v1/legal/search?case_respondents=%22Salazar+for+Congress%22&type=murs&hits_returned=20&from_hit=0&q=&api_key=NICAR16

### Completion criteria

- [x] `respondents` field has the capability for exact string match

### PR DESCRIPTION
**Pull request by cnlucas**
Draft PR adding the case_respondents query_string and then also switching everything over to simple_query_string as it doesn't seem like ES recommends using query_string in search boxes in production. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

Questions for Monday: 
When a filter is added--the current behavior is to include all documents where that field is not present. Is that what we want? 
Because highlight and document highlight are attached to query, this will show highlights for any searched term. Is this what we want? 
If we switch to simple, we lose the ability to specify field in the search. Is this something we need? 
Would this improve downtime? 
[API umbrella 400's](https://api.data.gov/admin/#/stats/logs?end_at=2024-06-28&query=%7B%22condition%22%3A%22AND%22%2C%22rules%22%3A%5B%7B%22id%22%3A%22request_path%22%2C%22field%22%3A%22request_path%22%2C%22type%22%3A%22string%22%2C%22input%22%3A%22text%22%2C%22operator%22%3A%22contains%22%2C%22value%22%3A%22legal%22%7D%2C%7B%22id%22%3A%22response_status%22%2C%22field%22%3A%22response_status%22%2C%22type%22%3A%22integer%22%2C%22input%22%3A%22number%22%2C%22operator%22%3A%22equal%22%2C%22value%22%3A400%7D%5D%2C%22valid%22%3Atrue%7D&start_at=2024-01-01)
Legal search[ downtime comparison ](https://docs.google.com/document/d/1a4BjykL5v0tmnZzCOi9z1PKeeOprua4aPGfT5JQpfZU/edit)
Would the syntax changes be hard to deal with in the FE? AND/OR to +/|? 
      notices? 
Need to improve testing
if we stick with query_string are the 400's currently being handled correctly? 

Should we allow wildcard? 
 analyze_wildcard
    (Optional, Boolean) If true, the query attempts to analyze wildcard terms in the query string. Defaults to false. 

We should keep this in mind if there's issues with standard:
https://www.elastic.co/guide/en/elasticsearch/reference/current/mixing-exact-search-with-stemming.html

## Summary (required)

- Resolves #5830

Switches from query_string to simple_query_string for our keyword search and switches case_respondents to simple_query_string from match

### Required reviewers

2-3 devs

## Impacted areas of the application

General components of the application that this PR will affect:

- legal search

## How to test

- You need the docs loaded for testing locally. Pat and I have been testing on dev with the standard analyzer. 
- activate your virtualenv
- pytest

http://127.0.0.1:5000/v1/legal/search/
http://127.0.0.1:5000/v1/legal/search/?case_respondents=jackson
http://127.0.0.1:5000/v1/legal/search/?case_respondents=%22Aaron%20Woolf%20for%20Congress%22
http://127.0.0.1:5000/v1/legal/search/?case_respondents=%22Friends%20of%20Jack%20Kingston%22

http://127.0.0.1:5000/v1/legal/search/?case_respondents=%22Casey%20|%20Michael%22
http://127.0.0.1:5000/v1/legal/search/?case_respondents=Fratto%20|%20Elissa

### CODE REVIEW

**Comment by patphongs** [comment]
@cnlucas I answered as many questions as I could before we meet on Monday, thanks again for all of your poignant research:

> When a filter is added--the current behavior is to include all documents where that field is not present. Is that what we want?

Since this is the current default behavior, I wouldn't refactor this just yet. For example, on the front end, a normal user won't be able to filter by respondents generically anyways, they would type into the corresponding respondents field within their specific datasets. In this case, only [MURs](https://www.fec.gov/data/legal/search/murs/) and [ADRs](https://www.fec.gov/data/legal/search/adrs/) have respondents fields to use. Therefore, we would always pass `type=murs` or `type=adrs`, and the user would only see the applicable dataset returned for respondents.

> Because highlight and document highlight are attached to query, this will show highlights for any searched term. Is this what we want?

This is also the current default behavior. I'm actually ok with the fact that the document highlights will highlight more fields than just document text, see research done by @tmpayton [here](https://github.com/fecgov/openFEC/issues/5831#issuecomment-2139637289). I do have a [word of caution](https://github.com/fecgov/openFEC/issues/5831#issuecomment-2176501927) that if we were to remove any of the other things from the highlights, we would need to ensure there are other ways to search those fields such as AO summary, statutes subheading, etc.

> If we switch to simple, we lose the ability to specify field in the search. Is this something we need?

We did not fully understand what the universal keyword search (`q`) was searching before, so your question actually brings into light something that I didn't even know existed. That you can actually search for a specific field like `q=name:republican` to look within the name field specifically. Therefore, I think having this removed by switching over to simple query string is ok since we didn't even know this was a possibility to begin with. If we truly wanted to search those specific fields, we would build a specific separate field for that capability.

> Would the syntax changes be hard to deal with in the FE? AND/OR to +/- |?

The API syntax changes for booleans should be ok, we can do a transform so that when the front end passes the query string to the API, we can change `AND` to `+`, `OR` to `|`. I'm already doing something similar for the eregs API, where the `OR` syntax is `|` as well, so I transform it in the call to the API, here's an [example in the code](https://github.com/fecgov/fec-cms/blob/1cf33dcb34863fb7556b6b354fdb9857782f1081/fec/legal/views.py#L160-L181). This way, the users won't have to change their normal behavior. But the trick is to know what the syntax transformation will look like when building out the query. As long as it's not too complex, the simple replacements should work.

**Comment by patphongs** [comment]
After doing some initial testing, I found an observation about case respondents when using simple query string exact match:

In the case of finding respondents where the `respondents` dictionary is built using `last_name, first_name middle_initial.`, it maybe challenging to find an exact string match with this syntax `case_respondents="karen grays"`. This will yield no results.

In order to find this match, you would need to utilize an `OR` statement such as this `case_respondents="grays%20|%20karen"`. Note that the syntax is last_name | first_name. 

Conversely, the reverse syntax will yield no results `case_respondents="karen%20|%20grays"`

This may be a difficult concept for users to understand.

**Comment by pkfec** [comment]
The `query_string` is strict on syntax, and errors in the input are NOT ignored. For example, when searched for "agency resources\"   query_string throws an server error because of the parsing issues. 

Example url:  https://www.fec.gov/data/legal/search/murs/?search_type=murs&sort=&search=%22agency+resources%5C%22&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=

`simple_query_string` query ignores any syntax error in the input criteria

Example url: https://dev.fec.gov/data/legal/search/murs/?search_type=murs&sort=&search=%22agency+resources%5C%22&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=

**Comment by cnlucas** [comment]
@patphongs I added minimum_should_match=2 which would mean if a user tried case_respondents=Karen Grays they would get only the MURs and ADRs with both Karen AND Grays. Unfortunately, this is still not perfect because sometimes there's a ton of respondents and maybe one is charles grays and another is karen smith. Then the user would be best served by using the exact string "Grays, Karen"

If this isn't sufficient we can consider: 
1. the old re-indexing solution---(I'm looking into seeing if any committee names have commas to see if we could use that as a delimiter. 
3. adding/switching to primary respondent search using name

**Comment by cnlucas** [comment]
We don't need to add minimum_should_match=2. The bug with + was just due to URL encoding. Karen + Grays should work with proper encoding of + to %2B. 
http://127.0.0.1:5000/v1/legal/search/?case_respondents=Karen%2BGrays

**Comment by cnlucas** [comment]
Closing as these changes are included in another PR

**Pull request closed without merging**
