### PR TITLE
Add max ten (10) limits for additional fields

### LINKED ISSUE #3902: Limit query variables for certain fields
Set up 10 filter limit for filters with performance issues.

**Completion criteria**
**Schedule A endpoint (schedules/schedule_a/):** 
- [ ] Limit 10 for:
- Name - `contributor_name`
- Zip - `contributor_zip`
- City - `contributor_city`
- Occupation - `contributor_employer`
- Employer - `contributor_occupation`

**Schedule B endpoint (schedules/schedule_b/):** 
- [ ] Limit 10 for:
- Recipient name or ID - `recipient_name` (takes ID or name)
- City  - `recipient_city`

**Schedule E endpoint (schedules/schedule_e/):** 
- [ ] Limit 10 for:
- Candidate name or ID (`candidate_id`)

We only seeing this many names and zip codes passed into a single query on 8/8 and 8/9/2019.  (during the media ask public to go to fec.gov and query contributors by name or zip code).  **Database performance is not an issue if this type of queries happening occasionally.**

Following are the sample queries:

**Names Query**
select * 
FROM disclosure.fec_fitem_sched_a 
	WHERE disclosure.fec_fitem_sched_a.is_individual = true AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date AND (disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Ware:* & Adams:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Scott:* & Allen:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Mark:* & Alderman:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('John:* & Aldock:*') OR disclosure.fec_fitem_sched_a.contributor_name_text @@ to_tsquery('Adrienne:* & Arsht:* & Elizabeth:* & Bagley:* & Jean:* & Bailey:* & Barbara:* & Bainum:* & Bruce:* & Bainum:* & Stewart:* & Bainum:* & Tomi:* & Bannister:* & Maurice:* & Bellan:* & Georgia:* & Berner:* & Megan:* & Beyer:* & Elizabeth:* & Birch:* & Tim:* & Broas:* & Anthony:* & Brown:* & Kathy:* & Brown:* & David:* & Burd:* & Dwight:* & amp:* & Toni:* & Bush:* & Wilfried:* & Busse:* & Roel:* & Campos:* & Stephen:* & and:* & Molly:* & Cashin:* & Hester:* & Clark:* & David:* & and:* & Rhonda:* & Cohen:* & Belinda:* & Coleman:* & Steve:* & and:* & Sandy:* & Cozen:* & Kelly:* & Craighead:* & Jehan:* & Christopher:* & De:* & La:* & Haye:* & Saint:* & Hilaire:* & Ted:* & Dintersmith:* & John:* & Duff:* & Jay:* & Dunn:* & David:* & Ferleger:* & Josh:* & and:* & Genine:* & Fidler:* & Joseph:* & amp:* & Marie:* & Field:* & Morton:* & amp:* & Norma:* & Lee:* & Funger:* & Matthew:* & amp:* & Marie:* & Garfield:* & Glenn:* & Gerstell:* & Carol:* & amp:* & Hank:* & Goldberg:* & Stuart:* & and:* & Suzanne:* & Grant:* & Ernest:* & Green:* & Keith:* & Harper:* & Scott:* & Harris:* & David:* & Hill:* & Jeffrey:* & Hoffman:* & Richard:* & Horowitz:* & Emmanuel:* & amp:* & Ogay:* & Irono:* & Frank:* & Islam:* & Kenneth:* & Jarin:* & Joseph:* & Kaempfer:* & Carolyn:* & Kaplan:* & Warren:* & Kaplan:* & Dan:* & and:* & Sunita:* & Leeds:* & Jeff:* & and:* & Cal:* & Leonard:* & Bel:* & Leong:* & Hong:* & Cliff:* & Levine:* & Rob:* & Liberatore:* & Terry:* & Terence:* & McAuliffe:* & Gerry:* & McGowan:* & David:* & McKean:* & Thomas:* & McLarty:* & Tom:* & McMillen:* & Lamell:* & McMorris:* & Nathan:* & Milikowsky:* & Judith:* & Miller:* & Constance:* & Milstein:* & Brenda:* & and:* & Mark:* & Moore:* & Thomas:* & and:* & Joyce:* & Moorehead:* & Faith:* & Morningstar:* & Jim:* & and:* & Bruce:* & Murray:* & Shekar:* & Narasimhan:* & Susan:* & Ness:* & Mark:* & Nichols:* & Peter:* & O:* & Keefe:* & Gov:* & Martin:* & O:* & Malley:* & Jo:* & Ousterhout:* & Spencer:* & Overton:* & Lazar:* & Palnick:* & Hilda:* & Pang:* & Fu:* & Shaunda:* & Patterson:* & Strachan:* & Carol:* & Pensky:* & John:* & Phillips:* & John:* & and:* & Mary:* & Register:* & John:* & Rezk:* & Adam:* & Riggs:* & Alfreda:* & Robinson:* & Cynthia:* & Ryan:* & Gabrielle:* & amp:* & Sunil:* & Sabharwal:* & Cynthia:* & Shapira:* & Rose:* & and:* & Cleveland:* & Slade:* & Sonjia:* & Smith:* & Earl:* & amp:* & Amanda:* & Stafford:* & George:* & Stevens:* & Ritchie:* & Tabachnick:* & Beth:* & Tomasello:* & Christy:* & amp:* & Scott:* & Wallace:* & Nancy:* & amp:* & Milton:* & Washington:* & John:* & Welch:* & Tom:* & Wheeler:* & Frank:* & White:* & Jr:* & Michael:* & Zeldin:*'));

**Zip codes query**

select * 
	FROM disclosure.fec_fitem_sched_a LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_1 ON disclosure.fec_fitem_sched_a.cmte_id = ofec_committee_history_mv_1.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_1.cycle LEFT OUTER JOIN ofec_committee_history_mv AS ofec_committee_history_mv_2 ON disclosure.fec_fitem_sched_a.clean_contbr_id = ofec_committee_history_mv_2.committee_id AND disclosure.fec_fitem_sched_a.two_year_transaction_period = ofec_committee_history_mv_2.cycle 
	WHERE disclosure.fec_fitem_sched_a.contb_receipt_dt >= '2018-01-01'::date AND disclosure.fec_fitem_sched_a.contb_receipt_dt <= '2020-12-31'::date AND ((disclosure.fec_fitem_sched_a.contbr_zip LIKE '95589' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95573' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95571' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95570' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95569' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95565' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95564' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95562' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95560' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95559' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95558' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95556' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95555' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95554' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95553' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95551' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95550' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95549' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95547' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95546' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95545' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95542' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95540' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95537' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95536' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95534' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95528' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95526' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95525' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95524' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95521' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95519' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95518' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95514' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95511' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95503' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95502' || '%') OR (disclosure.fec_fitem_sched_a.contbr_zip LIKE '95501' || '%')) ORDER BY disclosure.fec_fitem_sched_a.contb_receipt_amt DESC, disclosure.fec_fitem_sched_a.sub_id DESC LIMIT 100;

### Completion Criteria
- [ ] add validation to schedules endpoints for 10 names/zips

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

Resolves #3902
- Add max limits for additional fields (below)
- Add test coverage

**Schedule A endpoint (schedules/schedule_a/):** 
Limit 10 for:
- Name - `contributor_name`
- Zip - `contributor_zip`
- City - `contributor_city`
- Occupation - `contributor_employer`
- Employer - `contributor_occupation`

**Schedule B endpoint (schedules/schedule_b/):** 
Limit 10 for:
- Recipient name or ID - `recipient_name` (takes ID or name)
- City  - `recipient_city`

**Schedule E endpoint (schedules/schedule_e/):** 
Limit 10 for:
- Candidate name or ID (`candidate_id`)

## Schedule A
```
filters_with_max_count = [
    'committee_id',
    'contributor_name',
    'contributor_zip',
    'contributor_city',
    'contributor_employer',
    'contributor_occupation',
]
```
'committee_id',

http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&committee_id=C00223743&committee_id=C00223446&committee_id=C00223735&committee_id=C00222778&committee_id=C00222612&committee_id=C00224048&committee_id=C00222273&committee_id=C00222760&committee_id=C00223925&committee_id=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&committee_id=1&committee_id=2

'contributor_name',

http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_name=C00223743&contributor_name=C00223446&contributor_name=C00223735&contributor_name=C00222778&contributor_name=C00222612&contributor_name=C00224048&contributor_name=C00222273&contributor_name=C00222760&contributor_name=C00223925&contributor_name=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_name=1&contributor_name=2

'contributor_zip',

http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_zip=C00223743&contributor_zip=C00223446&contributor_zip=C00223735&contributor_zip=C00222778&contributor_zip=C00222612&contributor_zip=C00224048&contributor_zip=C00222273&contributor_zip=C00222760&contributor_zip=C00223925&contributor_zip=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_zip=1&contributor_zip=2

'contributor_city',

http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_city=C00223743&contributor_city=C00223446&contributor_city=C00223735&contributor_city=C00222778&contributor_city=C00222612&contributor_city=C00224048&contributor_city=C00222273&contributor_city=C00222760&contributor_city=C00223925&contributor_city=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_city=1&contributor_city=2

'contributor_employer',

http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_employer=C00223743&contributor_employer=C00223446&contributor_employer=C00223735&contributor_employer=C00222778&contributor_employer=C00222612&contributor_employer=C00224048&contributor_employer=C00222273&contributor_employer=C00222760&contributor_employer=C00223925&contributor_employer=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_employer=1&contributor_employer=2

'contributor_occupation',

http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_occupation=C00223743&contributor_occupation=C00223446&contributor_occupation=C00223735&contributor_occupation=C00222778&contributor_occupation=C00222612&contributor_occupation=C00224048&contributor_occupation=C00222273&contributor_occupation=C00222760&contributor_occupation=C00223925&contributor_occupation=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_occupation=1&contributor_occupation=2

## Schedule B

```
    filters_with_max_count = [
        'committee_id',
        'recipient_name',
        'recipient_city',
    ]

```

 'committee_id',

http://localhost:5000/v1/schedules/schedule_b/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00139998&committee_id=C00172189&committee_id=C00221820&committee_id=C00412304&committee_id=C00427526&committee_id=C00500975&committee_id=C00511055&committee_id=C00547679&committee_id=C00547828&committee_id=C00549972&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020&sort=-disbursement_date&per_page=30&committee_id=2

'recipient_name',

http://localhost:5000/v1/schedules/schedule_b/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&recipient_name=C00139998&recipient_name=C00172189&recipient_name=C00221820&recipient_name=C00412304&recipient_name=C00427526&recipient_name=C00500975&recipient_name=C00511055&recipient_name=C00547679&recipient_name=C00547828&recipient_name=C00549972&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020&sort=-disbursement_date&per_page=30&recipient_name=2

'recipient_city',

http://localhost:5000/v1/schedules/schedule_b/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&recipient_city=C00139998&recipient_city=C00172189&recipient_city=C00221820&recipient_city=C00412304&recipient_city=C00427526&recipient_city=C00500975&recipient_city=C00511055&recipient_city=C00547679&recipient_city=C00547828&recipient_city=C00549972&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020&sort=-disbursement_date&per_page=30&recipient_city=2

## Schedule E
```
    filters_with_max_count = [
        'committee_id',
        'candidate_id',
    ]
```

'committee_id',

http://localhost:5000/v1/schedules/schedule_e/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00139998&committee_id=C00172189&committee_id=C00221820&committee_id=C00412304&committee_id=C00427526&committee_id=C00500975&committee_id=C00511055&committee_id=C00547679&committee_id=C00547828&committee_id=C00549972&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020&per_page=30&committee_id=2

'candidate_id',

http://localhost:5000/v1/schedules/schedule_e/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&data_type=processed&candidate_id=C00139998&candidate_id=C00172189&candidate_id=C00221820&candidate_id=C00412304&candidate_id=C00427526&candidate_id=C00500975&candidate_id=C00511055&candidate_id=C00547679&candidate_id=C00547828&candidate_id=C00549972&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020&per_page=30&candidate_id=2

## Impacted areas of the application
List general components of the application that this PR will affect:

-  Schedule A, B, E  endpoints. Front-end is adding client-side validation.

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
feature/3996-max-10-cmte-ids | https://github.com/fecgov/openFEC/pull/4014

### CODE REVIEW

**Comment by patphongs** [comment]
@lbeaufort Can you add the ability to check which params have hit the limit? For example, if I have over 10 params for both `committee_id` and `contributor_name`, can you add both of those to the error message? Right now, it will put an error message on the first thing only, which may be confusing to the user to see another error after they have fixed the original error. 

http://localhost:5000/v1/schedules/schedule_a/?api_key=NICAR16&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00005561&committee_id=C00211763&committee_id=C00251751&committee_id=C00252403&committee_id=C00279315&committee_id=C00326975&committee_id=C00376939&committee_id=C00458679&committee_id=C00510701&committee_id=C00525600&committee_id=C00547489&contributor_name=albert&contributor_name=blaine&contributor_name=connie&contributor_name=demi&contributor_name=elephant&contributor_name=flanders&contributor_name=gilbert&contributor_name=hellen&contributor_name=isabella&contributor_name=janice&contributor_name=kimberly&contributor_name=latrice&sort=-contribution_receipt_date&per_page=30

**Example new error message:**

{
     "message": "Can only specify up to 10 values for:"
          "errorFields:" [
               "committee_id",
               "contributor_name"
          ]
     "status": 422
}

The reason I would like the errorFields put into a separate array is so that it's easier to possibly target on the front end. In case I need to also check the params, I can grab it from the `errorFields`.

**Comment by lbeaufort** [comment]
@patphongs I can make the change, but I think it makes the most sense to do the validation on the client side for the front end.

**Comment by lbeaufort** [comment]
@patphongs per our discussion, here's a better error message that specifies the fields over 10: 1b3491f812b6e6a63d04e571fabd915e2259c7a9 

```
{
message: "Can only specify up to 10 values for `contributor_name`, `contributor_zip`",
status: 422
}
```

Example for multiple "max 10" violations: 
http://localhost:5000/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&contributor_zip=C00223743&contributor_zip=C00223446&contributor_zip=C00223735&contributor_zip=C00222778&contributor_zip=C00222612&contributor_zip=C00224048&contributor_zip=C00222273&contributor_zip=C00222760&contributor_zip=C00223925&contributor_zip=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_zip=1&contributor_zip=2&contributor_name=C00223743&contributor_name=C00223446&contributor_name=C00223735&contributor_name=C00222778&contributor_name=C00222612&contributor_name=C00224048&contributor_name=C00222273&contributor_name=C00222760&contributor_name=C00223925&contributor_name=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true&contributor_name=1&contributor_name=2

**Comment by fec-jli** [comment]
@lbeaufort good jog, I review again, work as expected. Thanks
one more question, do we need update **endpoint description** or **parameter description** to tell user those 10 filter limitation warning?

**Comment by lbeaufort** [comment]
@fec-jli great point! We don't do that for committee_id now, but it would be good to include that in the parameter description. I created this follow-up issue: https://github.com/fecgov/openFEC/issues/4384

**Pull request merged**
