### PR TITLE
4958-upgrade flask

### LINKED ISSUE #4958: Update Flask to 2.0.1 (or latest 2.x)
### What we’re after

Update Flask to 2.0.1 (or latest 2.x). See https://github.com/pallets/flask/releases

Hopefully after we upgrade Flask to lates  version, we can unpin Jinja2 3.0.3 and Flask will pickup lates Jinja2.
https://github.com/fecgov/openFEC/pull/5091

### Related ticket(s)

- https://github.com/fecgov/openFEC/issues/4950

### Action item(s)

- [ ]  Adrdess any Pytest errors related to other package dependencies.

### Completion criteria

- [ ] Flask is updated to Flask to 2.0.1 (or latest 2.x)

### References/resources/technical considerations

[Changes for 2.0](https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0)

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary (required)

- Resolves #4958 

This is a major version upgrade with several breaking changes. Flask-Script has been deprecated, so it was removed and the Flask in-built CLI (which runs with click) was used to replace that functionality. There were a few changes to commands and some extra variables that need to be set which are noted in the README. **They will all be in the how-to below, but note that to run the server you must now use `flask run` or `python cli.py run`**

The commands used to be run with, for example: `python manage.py refresh_materialized`, in my first commit, but if I keep the CLI decorators on those functions I get a TypeError when I run the integration tests with pytest. 
If you run `pytest tests/integration/test_advisory_opinions.py -x` on the original commit you will see the errors. I fixed this issue by re-defining the functions for the CLI in a separate file (cli.py). If anyone has a better solution, or would like to offer suggestions on this item I would be very open to switching it up. 

 I've uploaded a .flaskenv file so we wouldn't have to manually export the FLASK_APP and FLASK_DEBUG variables in terminal. I added python-dotenv to the requirements.txt file which automatically loads the variables from the .flaskenv file. I ran locust tests (results below) and found no difference from our current speeds and failures. 

NOTE: I will update [the wiki](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-setup-and-test-locally) before the release is live.

I've noted that we have a ticket to fix the import app anti-pattern and think we should fix that separately. 

Sources I found helpful:
https://flask.palletsprojects.com/en/2.1.x/cli/
https://blog.miguelgrinberg.com/post/migrating-from-flask-script-to-the-new-flask-cli
https://click.palletsprojects.com/en/8.1.x/commands/

# Required reviewers
2-3 devs

## Impacted areas of the application

General components of the application that this PR will affect:

-  Local testing environment (specifically running any task in your terminal)

## How to test

- `gh pr checkout 5186`
- `pyenv install 3.8.12` 
- `pyenv virtualenv 3.8.12 venv-api3812` 
- `pyenv activate venv-api3812`
- `pip install -r requirements.txt` 
- `pip install -r requirements-dev.txt`
- `rm -rf node_modules` (optional step) (check for correct node version, switch with `nvm install 14.15.5`)
- `npm i && npm run build` 
- `dropdb cfdm_test`
- `createdb cfdm_test`
- `invoke create_sample_db`
- `pytest` (all tests should pass)
-  `python cli.py run` OR `flask run` and test swagger-ui
- try out the other CLI commands such as `python cli.py refresh_materialized`,  `python cli.py create_index` (any of the tasks in the wiki, but make sure to replace manage.py with cli.py and also remove flask options ie -i, -f,...would be happy to pair with anyone on this and running tasks)
-  deploy this branch to dev 
-  login to cloud.gov & make sure you're on dev 
- `cf tasks api` to see the tasks that have been tested 
- `cf run-task api --command "python cli.py display_snapshot_detail repository_archived_murs archived_murs*" -m 2G --name display_snapshot_detail" -m 2G --name display_snapshot_detail` (or any other task you'd like to run) 
- `cf tasks api` (Should run successfully---takes a few minutes depending on the command) 
- run locust testing (I already did this and the results are in a comment below.)

### CODE REVIEW

**Comment by cnlucas** [comment]
I fixed the pytest errors in my second commit, but I think it's pretty smelly and a not great solution. Can't seem to figure out how to get it to work without redefining the functions for the CLI.

**Comment by pkfec** [comment]
> * python manage.py run

^^ should be replace with python cli.py run

**Comment by pkfec** [comment]
@cnlucas  - [Management tasks](https://github.com/fecgov/openFEC/wiki/Elasticsearch-7.x.0-management-instruction#3-upload-individual-legal-document) that upload docs to Elasticsear hare not working on your branch. 
**Getting the following error:**
```
2022-07-12T19:21:00.47-0400 [APP/TASK/load_one_current_mur_pk/0] ERR * Tip: There are .env or .flaskenv files present. Do "pip install python-dotenv" to use them.
   2022-07-12T19:21:00.52-0400 [APP/TASK/load_one_current_mur_pk/0] ERR Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
   2022-07-12T19:21:00.52-0400 [APP/TASK/load_one_current_mur_pk/0] ERR Usage: cli.py [OPTIONS] COMMAND [ARGS]...
   2022-07-12T19:21:00.52-0400 [APP/TASK/load_one_current_mur_pk/0] ERR Try 'cli.py --help' for help.
   2022-07-12T19:21:00.52-0400 [APP/TASK/load_one_current_mur_pk/0] ERR Error: No such command 'load_current_murs'.
```

**Comment by pkfec** [comment]
@cnlucas  
 Update the logger name  to `logger = logging.getLogger(__name__)` in the following files

https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/regulations.py#L14
https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/statutes.py#L13

**Comment by cnlucas** [comment]
> @cnlucas Update the logger name to `logger = logging.getLogger(__name__)` in the following files
> 
> https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/regulations.py#L14 https://github.com/fecgov/openFEC/blob/develop/webservices/legal_docs/statutes.py#L13

Thanks, changes made!

**Comment by cnlucas** [comment]
Locust Testing Failures:
Screen Shot 2022-08-08 at 11 46 58 AM

**Review by pkfec — APPROVED** [review]
Well done @cnlucas. This is not an easy flask upgrade!

**Review by johnnyporkchops — APPROVED** [review]
Tested all steps in how-to-test locally and in tested tasks in Dev. Great work @Corrrine, thanks for a through how-to.

**Pull request merged**
