### PR TITLE
5522-add cmte_tp, filing_form filters add dep notice

### LINKED ISSUE #5522: Debts --committee_type filter
### What we’re after

To support [this design ](https://github.com/fecgov/fec-cms/issues/5819#issuecomment-1662644550)we would like to be able to filter by committee_type. 

### Related ticket(s)

(Include the tickets that either came before, after, or are happening in tandem with this new ticket)
- [x] https://github.com/fecgov/openFEC/issues/5510

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] Debts endpoint is filterable by committee_type (if we decide that's too much work we can add the filter for form_type

### References/resources/technical considerations

We had a sync between FE, Design and BE about whether we should filter by form_type and/or committee_type. Since committee type is the ultimate goal--just adding the filter for committee_type would be ideal. If we, for some reason, can't do that we should add the form_type filter instead.

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary 

- Resolves #5522 

Adds cmte_tp and filing_form filters to the debts endpoint. Adds deprecation notice to candidate_id filter. Candidate_id is <1% non-null. Removes mostly null fields from debts endpoint [to support the request to remove null fields from debts export. ](https://github.com/fecgov/openFEC/issues/5513)

### Required reviewers

2 devs

## Impacted areas of the application

-  Debts endpoint

## Screenshots

Screen Shot 2023-08-14 at 11 45 46 AM

Mostly null fields %'s
Screen Shot 2023-08-14 at 11 46 09 AM

## How to test
**Because I am removing fields, we need to include the migration file with the python changes. Do not deploy this PR to any space**
- Pull this PR
- in [webservices/common/models/itemized.py] change line 492 from:
__tablename__ = 'ofec_sched_d_mv'
to 
__tablename__ = 'ofec_sched_d_mv_cl_temp'

- make sure you're connected to dev
- flask run
-  http://127.0.0.1:5000/v1/schedules/schedule_d/?committee_type=H&page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
-  http://127.0.0.1:5000/v1/schedules/schedule_d/?filing_form=F3X&page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
- http://127.0.0.1:5000/v1/schedules/schedule_d/?&page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false
- http://127.0.0.1:5000/v1/schedules/schedule_d/?line_number=9&committee_type=P&page=1&per_page=20&sort=-coverage_end_date&sort_hide_null=false&sort_null_only=false&sort_nulls_last=false

I will delete my temp MV after review.

### CODE REVIEW

**Comment by hcaofec** [comment]
The name of the migration file should be V0283. @cnlucas

**Comment by cnlucas** [comment]
> The name of the migration file should be V0283. @cnlucas

Thank you, fixed.

**Review by tmpayton — APPROVED** [review]
Great work!

**Review by hcaofec — APPROVED** [review]
Tested with pytest and flyway migrate. Looks good!

**Pull request merged**
