### PR TITLE
feature/retrieve-cache-calls

### PR DESCRIPTION
**Pull request by pkfec**
To test this PR on your local, please follow the steps below:

1 . Checkout the feature branch for cached calls : **feature/retrieve-cache-calls**

2.  From CL,  **cf login --sso** , choose the  **dev** space.

3.  Get the following **S3** env variables and export them in  **openFEC** repo terminal.

- export access_key_id
- export secret_access_key
- export bucket
- export region
- export CACHE_ALL_REQUESTS

4. Also export the **SQLA_CONN** to **dev** DB instance (since our local  cfdm_test DB do not have any test data, we are pointing to dev DB)

5.  Bring the server up @openFEC terminal

6.  In a new terminal, bring the **redis** server up

7.  In a new terminal, bring the Celery Worker server up
For steps 6 and 7 follow the instruction here:
[https://github.com/fecgov/openFEC/wiki/Set-up-Redis-Celery-on-local-and-test-the-downloads]

8.  Bring the swagger api UP on a browser (http://localhost:5000/developers/). 

9.  Choose any endpoint and give it a try.

10. Check the Celery Worker terminal, that logs a message whether a request is cached successfully or not.

### CODE REVIEW

**Comment by ccostino** [comment]
@pkfec is this ready to be fully reviewed?  I see the `plz-review` label but this still has `[WIP]` in the title, so I wanted to check.

/cc @LindsayYoung

**Comment by LindsayYoung** [comment]
Took off the please review tag the remaining tasks are in https://github.com/18F/openFEC/issues/2913

**Comment by pkfec** [comment]
@ccostino and @LindsayYoung : Please review.

**Comment by pkfec** [comment]
@LindsayYoung and @ccostino Please review the latest changes.

**Comment by LindsayYoung** [comment]
@pkfec 'cache_all_requests' needs to be added to the manifests, correct?

**Comment by pkfec** [comment]
added the cache call env variable to the manifest-base.yml file

**Pull request merged**
