### PR TITLE
Upgrade flyway v10.7.1

### LINKED ISSUE #5699: Upgrade flyway to 10.6.0
### What we’re after
Upgrade flyway to latest version 10.6.0
flyway release note:
https://github.com/flyway/flyway/releases

### Action item(s)
- [x] Upgrade flyway to latest version 10.6.0
- [x] test on circleci

### Completion criteria
- [x] Flyway has been updated to latest version 10.6.0

### PR DESCRIPTION
**Pull request by tmpayton**
## Summary (required)

- Resolves #5699 

This ticket upgrades Flyway to the latest version 10.7.1.

## Impacted areas of the application

General components of the application that this PR will affect:

-  flyway migrations 

## How to test
1. Checkout this branch 
2. Uninstall flyway `brew uninstall flyway`
3. Install the latest version of flyway: 
Method One: `brew install flyway`
Method Two: Follow the [readme](https://github.com/fecgov/openFEC#installing-flyway) to install flyway version 10.7.1 manually 
4. Confirm version 10.7.1 was downloaded `flyway -v` 
5. `dropdb cfdm_test`
6. `createdb cfdm_test`
7. `invoke create_sample_db`
8. `pytest`

### CODE REVIEW

**Review by cnlucas — COMMENTED** [review]
This works for me, but should we update the README information about the conf file as this is no longer accurate for version 10?

**Comment by pkfec** [comment]
> This works for me, but should we update the README information about the conf file as this is no longer accurate for version 10?
> 
> Also, this will fix the most recent vulnerability #5708 putting here to close after merge

@tmpayton I second what @cnlucas mentioned here ^^ . flyway v10.7 is now using `flyway.toml` configuration file 

The following section in README.md  should be updated to reflect the latest config changes:

Screen Shot 2024-02-01 at 12 43 34 PM

**Review by pkfec — COMMENTED** [review]
Flyway v10 comes with flyway.toml configuration file. This section should be updated to  to reflect the latest config changes:

**Comment by fec-jli** [comment]
1)In data/flyway/build.gradle, should be 10.7.1 ?
2)For README file, download flyway command line jar way won't work anymore, we have to install flyway through Howebrew to install. Could you clean download flyway command line part of paragraph? Thanks

**Comment by tmpayton** [comment]
@cnlucas @pkfec @fec-jli thank you for the thorough review. I made the requested changes!

**Review by cnlucas — APPROVED** [review]
Great job, thanks @tmpayton

**Review by fec-jli — APPROVED** [review]
Looks great. Thanks

**Pull request merged**
