### PR TITLE
Feature/switch sched a

### PR DESCRIPTION
**Pull request by fecjjeng**
## Summary (required)

After the switch, the schedule_b queries will be pointed to fecp-driven fec_fitem_sched_a tables. When run the application locally, try api for schedule_a. 

- Addresses # 3088

## How to test the changes locally
After the switch, the schedule_b queries will be pointed to fecp-driven fec_fitem_sched_a tables. When run the application locally, try api for schedule_a
https://api.open.fec.gov/developers/#!/receipts/get_schedules_schedule_a
Make sure the API is still working.

## Impacted areas of the application
List general components of the application that this PR will affect:
This issue will impact schedule_a related API. However, the changes should be transparent to the users.
  

## Related PRs
List related PRs against other branches:

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

### CODE REVIEW

**Comment by fecjjeng** [comment]
Indexes:
These sets of tables have most indexes the current ofec_sched_a tables had, except some of these indexes appears not to be used by postgresql db engine with API calls.
- contbr_zip:  
contbr_zip is using gin_trgm_ops.  Combination gin_trgm_ops with neither contb_receipt_dt nor contb_receipt_amt is used by optimizer.
- is_individual: 
not used by optimizer, with or without combination with contb_receipt_dt nor contb_receipt_amt
- pg_date:  
not used by API nor new partition process, so not indexed
- contrib_occ_text (combination with contb_receipt_dt or contb_receipt_amt): 
Sometime used, depending on the distribution of the data.  So still built the indexes on the new tables.
- two_year_transaction_period
whole table has the same two_year_transaction_period, no need to have index on it
however, since SQLAlchemy always include it in the query, it can make optimizer use the two_year_transaction_period_dt_sub_id or two_year_transaction_period_amt_sub_id index 
seems more efficient than using skip first column index or combined two indexes 
- There are two sets of indexes on current ofec_sched_a tables are repeats (with same column combination, type and position, but different name).  So only keep one of these indexes per set.

**Comment by ccostino** [comment]
Are we sure about the `is_individual` index not being used at all?  Also, that's interesting regarding the `two_year_transaction_period`; I wonder why that is.

**Comment by fecjjeng** [comment]
-- ********************************
--	is_individual
-- ********************************
/*
Following is the summery what I tried for the is_individual
-- tried
-- only been used when "order by" not used; and is_individual = false
CREATE INDEX idx_fec_fitem_sched_a_2017_2018_is_individual
  ON disclosure.fec_fitem_sched_a_2017_2018
  USING btree
  (is_individual);

-- tried, not used by optimizer
CREATE INDEX idx_fec_fitem_sched_a_2017_2018_is_individual_dt_sub_id
  ON disclosure.fec_fitem_sched_a_2017_2018
  USING btree
  (is_individual, contb_receipt_dt, sub_id);

-- tried, not used by optimizer
CREATE INDEX idx_fec_fitem_sched_a_2017_2018_is_individual_amt_sub_id
  ON disclosure.fec_fitem_sched_a_2017_2018
  USING btree
  (is_individual, contb_receipt_amt, sub_id);
*/

I did not record all the test result I had with the explain plan, but below is some of the example:

select cmte_id, two_year_transaction_period, contbr_zip, contb_receipt_amt, contb_receipt_dt
FROM disclosure.fec_fitem_sched_a
WHERE two_year_transaction_period = 2018 
AND is_individual= true
ORDER BY contb_receipt_dt , sub_id
LIMIT 100;

-- ++++++++++++++++++++++++++
CREATE INDEX idx_fec_fitem_sched_a_2017_2018_is_individual_dt_sub_id
  ON disclosure.fec_fitem_sched_a_2017_2018
  USING btree
  (is_individual, contb_receipt_dt, sub_id);
  
ANALYZE disclosure.fec_fitem_sched_a_2017_2018;
-- ++++++++++++++++++++++++++

"Limit  (cost=0.58..396.09 rows=100 width=47) (actual time=0.028..0.308 rows=100 loops=1)"
"  ->  Merge Append  (cost=0.58..173369075.34 rows=43834558 width=47) (actual time=0.027..0.302 rows=100 loops=1)"
"        Sort Key: fec_fitem_sched_a.contb_receipt_dt, fec_fitem_sched_a.sub_id"
"        ->  Sort  (cost=0.01..0.02 rows=1 width=130) (actual time=0.008..0.008 rows=0 loops=1)"
"              Sort Key: fec_fitem_sched_a.contb_receipt_dt, fec_fitem_sched_a.sub_id"
"              Sort Method: quicksort  Memory: 25kB"
"              ->  Seq Scan on fec_fitem_sched_a  (cost=0.00..0.00 rows=1 width=130) (actual time=0.004..0.004 rows=0 loops=1)"
"                    Filter: (is_individual AND (two_year_transaction_period = '2018'::numeric))"
"        ->  Index Scan using idx_fec_fitem_sched_a_2017_2018_dt_sub_id on fec_fitem_sched_a_2017_2018  (cost=0.56..172821143.34 rows=43834557 width=47) (actual time=0.019..0.288 rows=100 loops=1)"
"              Filter: (is_individual AND (two_year_transaction_period = '2018'::numeric))"
"              Rows Removed by Filter: 8"
"Planning time: 1.719 ms"
"Execution time: 0.348 ms"

-- ****************************
--  two_year_transaction_period
-- ****************************
explain analyze
select 
cmte_id, two_year_transaction_period, contbr_zip, contb_receipt_amt, contb_receipt_dt, contributor_occupation_text
FROM ofec_sched_a_2017_2018
WHERE 
--two_year_transaction_period = 2018 
--AND 
(contb_receipt_dt, sub_id) > ('2018-03-26'::DATE, '4042720181530524007')
ORDER BY contb_receipt_dt, sub_id 
LIMIT 100

"Limit  (cost=1800628.41..1800628.66 rows=100 width=78) (actual time=1350.979..1351.028 rows=100 loops=1)"
"  ->  Sort  (cost=1800628.41..1802306.31 rows=671160 width=78) (actual time=1350.977..1350.996 rows=100 loops=1)"
"        Sort Key: contb_receipt_dt, sub_id"
"        Sort Method: top-N heapsort  Memory: 39kB"
"        ->  Bitmap Heap Scan on ofec_sched_a_2017_2018  (cost=48474.06..1774977.16 rows=671160 width=78) (actual time=184.994..1016.658 rows=834192 loops=1)"
"              Recheck Cond: (ROW(contb_receipt_dt, sub_id) > ROW('2018-03-26'::date, '4042720181530524007'::numeric))"
"              Heap Blocks: exact=184230"
"              ->  Bitmap Index Scan on idx_ofec_sched_a_2017_2018_sub_id_date_amt  (cost=0.00..48306.26 rows=671160 width=0) (actual time=135.173..135.173 rows=835140 loops=1)"
"                    Index Cond: (ROW(contb_receipt_dt, sub_id) > ROW('2018-03-26'::date, '4042720181530524007'::numeric))"
"Planning time: 0.327 ms"
"Execution time: 1352.751 ms"


explain analyze
select 
cmte_id, two_year_transaction_period, contbr_zip, contb_receipt_amt, contb_receipt_dt, contributor_occupation_text
FROM ofec_sched_a_2017_2018
WHERE 
two_year_transaction_period = 2018 
AND 
(contb_receipt_dt, sub_id) > ('2018-03-26'::DATE, '4042720181530524007')
ORDER BY contb_receipt_dt, sub_id 
LIMIT 100

"Limit  (cost=0.56..174.89 rows=100 width=78) (actual time=0.025..0.198 rows=100 loops=1)"
"  ->  Index Scan using idx_ofec_sched_a_2017_2018_two_year_transaction_period_dt on ofec_sched_a_2017_2018  (cost=0.56..1170007.95 rows=671160 width=78) (actual time=0.024..0.173 rows=100 loops=1)"
"        Index Cond: ((two_year_transaction_period = 2018) AND (ROW(contb_receipt_dt, sub_id) > ROW('2018-03-26'::date, '4042720181530524007'::numeric)))"
"Planning time: 0.356 ms"
"Execution time: 0.250 ms"

**Comment by ccostino** [comment]
Interesting, thank you @fecjjeng!  I wonder if there's another way to setup that `is_individual` index though to make it work/useful.  Seeing as how that's not the case right now though, we should just move forward with what we have and can come back to it again at a later time.

**Pull request merged**
