### PR TITLE
[MERGE WITH GITFLOW] Release/public 20201222

### PR DESCRIPTION
**Pull request by pkfec**
Sprint 13.9 release branch. @pkfec will deploy the release on 12/22/2020

### CODE REVIEW

**Review by fec-jli — APPROVED** [review]
good.

**Review by lbeaufort — COMMENTED** [review]
Should the `fec-s3-api` service be created before this is deployed?

**Comment by lbeaufort** [comment]
> fec-s3-api

Plan is to create it on Monday

**Comment by pkfec** [comment]
> Should the `fec-s3-api` service be created in `prod` before this is deployed?

Renaming the existing service from`fec-s3-api` to `fec-s3-prod` should be good. Wont take that long.

**Pull request merged**
