### PR TITLE
Feature/4112 schedule h4 endpoint

### LINKED ISSUE #4112: Create prototype for schedule_h4 endpoint
### Summary

In preparation for our H schedule Data Design Studio the back-end team suggested that a prototype for H schedule data may be useful to help analysts and other interested users to understand the endpoint functionality. Considering schedule H4 data is most similar to a schedule B data, it was suggested that the Schedule B endpoint would a good template for creating this prototype.

THIS SHOULD NOT BECOME A BLOCKER FOR THE DATA DESIGN STUDIO.

**Previous tickets:** #3341 (H4 data request -- ~currently in icebox~ closed)

What's needed
- duplicate functionality for schedule b endpoint for a prototype of `fec_fitem_sched_h4`
- this will be a starting point to determine additional filters (or potentially removal of filters)
- Users may be interested in being able to cross reference `fec_fitem_sched_b`

### completion criteria
- [x] prototype is available for use in the data design studio.
- [x] notify @JonellaCulmer that the prototype is ready for use.
- [x] write basic test cases (may need to revise these based on "Future work" below

### Future work
- Create a data table of H schedule data (PI 12)

### PR DESCRIPTION
**Pull request by jason-upchurch**
## Summary (required)

- Resolves #4112 
- This is a basic first iteration working version of a new `schedule_h4` endpiont. Subsequent issues will be iterated over to refine this endpoint and possibly generalize to schedule H (rather than just H4). Additional schedule_h4 specific endpoints may also be generated using this branch as a base.

## How to test the changes locally
- checkout out branch
- pytest

To test the published version:
- uncomment the line in `rest.py`: `# apidoc.register(sched_h4.ScheduleH4View, blueprint='v1')`
- run local api, point to a db having schedule h4 data, and inspect the schedule h4 endpoint under the "disbursements" tag to see that it functions.

## Impacted areas of the application
disbursements api endpoint

### CODE REVIEW

**Comment by jason-upchurch** [comment]
@fec-jli I removed from `schemas.py` several names that were associated with `sched_b` but not `sched_h4`. Thank you for your help identifying these.

**Comment by hcaofec** [comment]
Followed the steps for testing, all tests passed. 
If the lines of code here are not needed, should it be removed?
https://github.com/fecgov/openFEC/pull/4123/files#diff-d3314ee984ebb5faeab53a4b62b81e63R40

**Comment by jason-upchurch** [comment]
> Followed the steps for testing, all tests passed.
> If the lines of code here are not needed, should it be removed?
> https://github.com/fecgov/openFEC/pull/4123/files#diff-d3314ee984ebb5faeab53a4b62b81e63R40

@hcaofec since we're iterating I'm ok leaving it--I'm sure more will be added and removed as we refine (but yes, I think the end product should not have unused code commented out such as we have in other places).

**Comment by fec-jli** [comment]
good. Could you add test coverage for all filters? Thanks

**Comment by jason-upchurch** [comment]
> good. Could you add test coverage for all filters? Thanks

Hi @fec-jli cc @PaulClark2 I think we should add filter test cases, but not to this PR. I think we should add them once the design studio has identified which filters should stay and which ones should go. The test case I added was to verify I could connect a prototype, and I think more meaningful and relevant tests cases should be added as we flesh out the endpoint, but I don't think it should be a blocker to merging this work.

**Comment by fec-jli** [comment]
> > good. Could you add test coverage for all filters? Thanks
> 
> Hi @fec-jli cc @PaulClark2 I think we should add filter test cases, but not to this PR. I think we should add them once the design studio has identified which filters should stay and which ones should go. The test case I added was to verify I could connect a prototype, and I think more meaningful and relevant tests cases should be added as we flesh out the endpoint, but I don't think it should be a blocker to merging this work.

Thanks. I think you can add now, the endpoint will be used for all api users, not only by our fec website design. all filters in the resources/sched_h4.py should have test converge. Thanks

**Comment by jason-upchurch** [comment]
> > > good. Could you add test coverage for all filters? Thanks
> > 
> > 
> > Hi @fec-jli cc @PaulClark2 I think we should add filter test cases, but not to this PR. I think we should add them once the design studio has identified which filters should stay and which ones should go. The test case I added was to verify I could connect a prototype, and I think more meaningful and relevant tests cases should be added as we flesh out the endpoint, but I don't think it should be a blocker to merging this work.
> 
> Thanks. I think you can add now, the endpoint will be used for all api users, not only by our fec website design. all filters in the resources/sched_h4.py should have test converge. Thanks

Hi @fec-jli--thank you, I see the misunderstanding. This is not being published yet.

**Comment by jason-upchurch** [comment]
@hcaofec @fec-jli I've removed comments Helen requested and added additional pytest coverage to any of the filters that remained. Are you able to review?

**Pull request merged**
