### PR TITLE
5982-Fix arch mur and current mur sort

### LINKED ISSUE #5982: Incorrect MUR sort order
### What we’re after

The sort order for MURs seem to be incorrect. This seems to be the case when current MURs end and archived MURs start. Example website link: https://www.fec.gov/data/legal/search/murs/?search=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=3080&limit=20&sort=#results-murs

Screenshot 2024-09-18 at 1 38 16 PM

### Completion criteria

- [ ] MURs and archived MURs are sorted correctly

### PR DESCRIPTION
**Pull request by fec-jli**
## Summary (required)
This PR will fix incorrect order for current MURs and Arch MURs.

### Notes:
1)after merge, we should reload all case legal document and archived MURs documents in dev
2)after cut, we should reload all case legal document and archived MURs documents in stage
3)after deploy production, we should reload all case legal document and archived MURs documents in prod.

- Resolves #5982 

### Required reviewers

1-2 devs

## Impacted areas of the application
'/legal/search/'

General components of the application that this PR will affect:
current_cases.py
archived_murs.py
legal.py

Ref [add test in legal/search](https://github.com/fecgov/openFEC/issues/6009)

## How to test
1)Check branch
2)setup local ES
3)load some arch mur and current mur data to local ES
```
python cli.py display_index_alias
python cli.py create_index case_index
python cli.py create_index arch_mur_index

python cli.py delete_index case_index
python cli.py delete_index arch_mur_index

python cli.py load_current_murs 4250
python cli.py load_current_murs 4012
python cli.py load_current_murs 3987
python cli.py load_current_murs 3774
python cli.py load_current_murs 3620
python cli.py load_current_murs 2804R
python cli.py load_current_murs 2314

python cli.py load_archived_murs 2465
python cli.py load_archived_murs 2455
python cli.py load_archived_murs 2454
python cli.py load_archived_murs 2446
python cli.py load_archived_murs 2445
python cli.py load_archived_murs 2444
python cli.py load_archived_murs 2443
python cli.py load_archived_murs 2441
python cli.py load_archived_murs 2439
python cli.py load_archived_murs 2435
python cli.py load_archived_murs 2431
python cli.py load_archived_murs 2429
python cli.py load_archived_murs 2423
```
4)Test mur sort
http://127.0.0.1:5000/v1/legal/search/?type=murs&sort=-case_no
http://127.0.0.1:5000/v1/legal/search/?type=murs&sort=case_no

5)load some `adr` and `admin_fines` data and test sort
python cli.py load_adrs
python cli.py load_admin_fines

http://127.0.0.1:5000/v1/legal/search/?type=admin_fines&sort=-case_no
http://127.0.0.1:5000/v1/legal/search/?type=admin_fines&sort=case_no
http://127.0.0.1:5000/v1/legal/search/?type=adrs&sort=-case_no
http://127.0.0.1:5000/v1/legal/search/?type=adrs&sort=case_no

6)load some `ao` data and test sort
python cli.py load_advisory_opinions
http://127.0.0.1:5000/v1/legal/search/?type=advisory_opinions&sort=ao_no
http://127.0.0.1:5000/v1/legal/search/?type=advisory_opinions&sort=-ao_no

7)Test in dev compare with prod
in prod:
https://www.fec.gov/data/legal/search/murs/?search=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=3080&limit=20&sort=#results-murs

in dev:
https://dev.fec.gov/data/legal/search/murs/?search=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=&offset=3080&limit=20&sort=#results-murs

### CODE REVIEW

**Comment by fec-jli** [comment]
When you see a “R” case, it means that the case has been remanded or in plain language, reopened. This can be due to a court case decision or a request for legal consideration.
These are separate cases.

**Review by pkfec — APPROVED** [review]
Tested your changes in dev space. mur sort now works well. Thanks @fec-jli

**Review by tmpayton — APPROVED** [review]
Really great job @fec-jli I tested on dev and it works correctly.

**Review by cnlucas — APPROVED** [review]
Works well for me, thanks @fec-jli

**Pull request merged**
