### PR TITLE
[WIP] Feature/archive murs partial pdfs

### PR DESCRIPTION
**Pull request by rjayasekera**
## Summary (required)
There are about 9 Archive MURs that contains multiple pdf files.  We need to be able to load all associated PDF files when pass in a MUR number to `manage.py load_archived_murs` program with either -f (from MUR number) or -s (specific MUR number)

- Resolves # [[_3234_](https://github.com/fecgov/openFEC/issues/3234)]

_Include a summary of proposed changes._
Change the RegEx within load_archived_murs function in load_legal_docs.py to be able to pick up all parts of PDFs associated with a MUR number. Then in process_murs go thru a loop to load them one at a time to ES and S3.  Change some variable names to better identify them with their intended purpose.

## How to test the changes locally
- Pull down the branch to local environment
- Point SQLA_CONN to DEV DB
- Set up S3 bucket variables
- Load MURS using -s and -f flags 

## Impacted areas of the application
List general components of the application that this PR will affect:
Loading of Archive MURS

## Related PRs
List related PRs against other branches:
None

branch | PR
------ | ------
fix/other_pr | [link]()
feature/other_pr | [link]()

### CODE REVIEW

**Comment by vrajmohan** [comment]
It would be easier to review this if we cleaned up the commits. Right now, changes introduced by a commit are overwritten by subsequent commits within the same PR.

**Comment by rjayasekera** [comment]
@vrajmohan, I squash all my commits into one commit. Please review the changes. Thanks.

**Comment by vrajmohan** [comment]
Sorry, but this makes it harder to review. It would be better to break up the changes as:
- Pure refactoring (no change in functionality)
- Removal of multiprocessing
- Support for multiple PDFs (this in turn can be broken into multiple logical changes if necessary)

**Comment by rjayasekera** [comment]
I thought we get rid or multiprocessing by removing the following code
`    murs = zip(range(len(rows)), [len(rows)] * len(rows), rows)
    processes = int(num_processes)
    maxtasksperchild = int(tasks_per_child) if tasks_per_child else None
    with Pool(processes=processes, maxtasksperchild=maxtasksperchild) as pool:
        pool.map(process_mur, murs, chunksize=1)
`

**Comment by vrajmohan** [comment]
Right, having these as "logical commits that tell a story" make it easier for the reviewer as well as for future investigations.

**Comment by rjayasekera** [comment]
Close this PR and open the following:
https://github.com/fecgov/openFEC/pull/3278

**Comment by JonellaCulmer** [comment]
@rjayasekera Are you at a point where you can close this PR and just leave the more updated PR? It appears that is where the more current discussion is happening anyway.

**Pull request closed without merging**
