### PR TITLE
create new materialized view to include form_3 submitted by pac and party

### PR DESCRIPTION
**Pull request by hcaofec**
## Summary 

Addresses [#3103](https://github.com/fecgov/openFEC/issues/3103) 

-V0081 was added to data/migration.  

## How to test the changes locally

 - If local database has enough sample data, the materialized view should have this row:
FILE_NUM | CMTE_ID | FORM_TP | RPT_TP | RPT_YR | BEGIN_IMAGE_NUM | 
1206344 | C00156554 | F3 | YE | 2017 | 201801240300187403

- otherwise, run a select statement against the query part only

### CODE REVIEW

**Comment by vrajmohan** [comment]
Is this going to replace `public.ofec_reports_pacs_parties_mv`? If not, can it be defined using `public.ofec_reports_pacs_parties_mv`?

**Comment by vrajmohan** [comment]
Also, if it is not going to replace `ofec_reports_pacs_parties_mv`, can it be a regular view defined using `ofec_reports_pacs_parties_mv`?

**Comment by hcaofec** [comment]
Eventually, the api endpoint that is using ofec_reports_pacs_parties_mv now will switch to this new materialized view.   If ofec_reports_pacs_parties_mv is not used by any other api, it will be dropped.

The logic from ofec_reports_pacs_parties_mv was copied here instead of using the view itself is to reduce the dependency between materialized views.

**Comment by hcaofec** [comment]
I guess this view will replace public.ofec_reports_pacs_parties_mv

**Comment by hcaofec** [comment]
Thanks.  I will modify the script

**Pull request merged**
