### PR TITLE
5000-Add MV refresh process to ReadMe

### LINKED ISSUE #5000: Add MV refresh process to ReadMe
### What we’re after
We should add the process to refresh the materialized views to the README.

### Action item(s)/Completion Criteria

- [ ] ReadMe includes MV refresh process

### PR DESCRIPTION
**Pull request by cnlucas**
## Summary (required)

- Resolves #5000 

Adds MV refresh process to ReadMe and corrects small typo. 

### Required reviewers
1 reviewer

## Impacted areas of the application

General components of the application that this PR will affect:

-  OpenFEC ReadMe

## Screenshots
Screen Shot 2021-12-08 at 9 32 53 PM

### CODE REVIEW

**Comment by fec-jli** [comment]
Thanks you work on this.
one small comment, we can tail the log in terminal easily. Can we think to add these lines? Thanks
---------
Open a terminal to tail the logs:
`cf logs api`
---------

**Review by fec-jli — APPROVED** [review]
Good. Thanks.

**Comment by fec-jli** [comment]
one more change. Could you change `production` to `${cf_space}` ? Thanks

**Comment by cnlucas** [comment]
Thanks again @fec-jli!

**Pull request merged**
