### PR TITLE
Increase maximum number of committeeIDs to 10

### LINKED ISSUE #3996: Increase committee ID limit for schedule A to 10
https://api-stage.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=false&committee_id=C00223743&committee_id=C00223446&committee_id=C00223735&committee_id=C00222778&committee_id=C00222612&committee_id=C00224048&committee_id=C00222273&committee_id=C00222760&committee_id=C00223925&committee_id=C00213850&two_year_transaction_period=1996&two_year_transaction_period=1994&contributor_state=CA&sort=-contribution_receipt_date&per_page=30&is_individual=true

Front end use case: Bob Dole's authorized committees

**Completion criteria**
- [x] Increase the limit to 10
- [x] Test performance
- [x] Add a follow-up ticket to the front end to prevent users from adding more than 10 committee IDs and throw validation if more than 10 are passed https://github.com/fecgov/fec-cms/issues/3272

### PR DESCRIPTION
**Pull request by lbeaufort**
## Summary (required)

- Resolves #3996

Increase maximum number of committeeIDs for itemized resource tables

## How to test the changes locally

-  Make sure transaction endpoints return results for up to 10 committee IDs
http://127.0.0.1:5000/v1/schedules/schedule_a/?api_key=&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00031781&committee_id=C00107391&committee_id=C00139998&committee_id=C00171538&committee_id=C00187435&committee_id=C00188888&committee_id=C00250191&committee_id=C00329706&committee_id=C00364091&committee_id=C00401224&committee_id=C00412304&committee_id=C00547679&sort=-contribution_receipt_date&per_page=30

- Make sure transaction endpoints return validation error message for **over** 10 committee IDs
http://localhost:5000/v1/schedules/schedule_a/?api_key=28Y8q8XFocq8yhKfBzzhUJXjFj2JHCZzIv4P2KIK&sort_hide_null=false&sort_nulls_last=false&data_type=processed&committee_id=C00031781&committee_id=C00107391&committee_id=C00139998&committee_id=C00171538&committee_id=C00187435&committee_id=C00188888&committee_id=C00250191&committee_id=C00329706&committee_id=C00364091&committee_id=C00401224&committee_id=C00412304&committee_id=C00547679&sort=-contribution_receipt_date&per_page=30

## Impacted areas of the application
List general components of the application that this PR will affect:

-  Transaction datatabes
- Click-through for "Where contributions come from" map

### CODE REVIEW

**Comment by pkfec** [comment]
@lbeaufort the change looks great and works fine if i look up for committee(s) other than `ACT BLUE`. Out of the 10 committees if anyone tries to search for one ACTBLUE  committee we all know for sure the DB performance will be very slow.

Did you run locust tests with 10 different committees and notice any performance hit on the DB?  Could you post your findings in the PR?

**Comment by lbeaufort** [comment]
@pkfec I didn't run locust tests because I didn't really have anything to compare results to. 10 committee IDs will always be slower than 5 committeeIDs - I just tested the known use cases to make sure they could return results.

**Comment by pkfec** [comment]
I trust your judgement. if we run the locust test and have a record of it somewhere, it will be very useful to refer and compare the results, when there is a slow query or performance hit on DB.

**Comment by lbeaufort** [comment]
@pkfec I agree it would be good to do the test. I’m working on some other locust tests for #3965 so I can test these changes too

**Pull request merged**
