### PR TITLE
[WIP] Remove 5-committee restriction from ItemizedResource

### LINKED ISSUE #3209: Investigate and expand committee_id limit beyond five values
**What we're after:** For candidates with more than 5 authorized committees, the individual contributions table does not yield results. We need to explore expanding that 5 committee_id limit so that the website does not appear non-function and so we can return accurate results. This, of course, must be balanced with performance. 

**Example:** Select a figure from the individual contributions table on the election profile page to recreate problem. 
Tim Kaine: 
**Election profile page:** https://www.fec.gov/data/elections/senate/VA/2018/?tab=contributions 
**Individual contributions data table:** https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&committee_id=C00495358&committee_id=C00572388&committee_id=C00631960&committee_id=C00648071&committee_id=C00648089&committee_id=C00648238&committee_id=C00662114&min_date=01%2F01%2F2017&max_date=06%2F12%2F2018&min_amount=0.00&max_amount=200.00 
**API call:** https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&sort_hide_null=true&committee_id=C00495358&committee_id=C00572388&committee_id=C00631960&committee_id=C00648071&committee_id=C00648089&committee_id=C00648238&committee_id=C00662114&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F12%2F2018&min_amount=0.00&max_amount=200.00&sort=-contribution_receipt_date&per_page=30&is_individual=true 

- [ ] Make sure this addresses https://github.com/fecgov/fec-cms/issues/1656

### PR DESCRIPTION
**Pull request by lbeaufort**
- [ ] Do load testing with more committees. Figure out if we should raise the restriction instead

## Summary (required)

- Resolves #3209 and Resolves https://github.com/fecgov/fec-cms/issues/1656

_Remove 5-committee restriction from ItemizedResource (schedule data). Add large schedule B locust test. Confirmed that there isn't a performance hit w/[Locust tests](feature/remove-5-committee-restriction)_

## How to test the changes locally

- http://localhost:5000/v1/schedules/schedule_a/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&committee_id=C00431445&committee_id=C00434357&committee_id=C00443317&committee_id=C00446195&committee_id=C00446435&committee_id=C00450809&committee_id=C00451393&committee_id=C00455949&committee_id=C00462176&committee_id=C00494740&committee_id=C00496992&committee_id=C00507830&committee_id=C00519694&committee_id=C00528364&committee_id=C00529842&two_year_transaction_period=2012&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00&sort=-contribution_receipt_date&per_page=30&is_individual=true
- http://localhost:5000/v1/schedules/schedule_b/?api_key=DEMO_KEY&sort_hide_null=true&committee_id=C00431171&committee_id=C00493726&committee_id=C00502708&committee_id=C00505107&committee_id=C00518282&committee_id=C00518852&committee_id=C00523050&committee_id=C00528513&committee_id=C00529859&committee_id=C00532671&two_year_transaction_period=2012&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00&is_individual=true

## Impacted areas of the application
List general components of the application that this PR will affect:

-  Individual contributions search, example: https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2012&committee_id=C00431445&committee_id=C00434357&committee_id=C00443317&committee_id=C00446195&committee_id=C00446435&committee_id=C00450809&committee_id=C00451393&committee_id=C00455949&committee_id=C00462176&committee_id=C00494740&committee_id=C00496992&committee_id=C00507830&committee_id=C00519694&committee_id=C00528364&committee_id=C00529842&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00

### CODE REVIEW

**Comment by vrajmohan** [comment]
Does it make sense to have a larger limit or to remove it entirely? I see that you have a test with 6 committees; does it make sense to see at what point we have a performance impact?

**Comment by vrajmohan** [comment]
I would defer to @JonellaCulmer. Perhaps we should pull up some statistics on candidates and committees.

**Comment by PaulClark2** [comment]
Can we determine when we take a performance hit? If we can an larger limit makes sense. We should allow folks to select as many committees as our system will support and remain performant. If this isn't easy to determine, I suggest we start with an upper limit of 20. We can see how our system performs and if folks ask for a larger limit.

**Comment by lbeaufort** [comment]
Sounds good to me. @jwchumley said he would get me a list of the candidate ID's with the highest number of linked committee ID's. I'm testing the examples in https://github.com/fecgov/fec-cms/issues/1656 to start.

**Comment by jwchumley** [comment]
Here are the top ten in this cycle. This includes Joint Fundraisers.
S2WI00219	19
S6MO00305	16
S6MT00162	12
S8FL00166	12
S6OH00163	11
S8NV00156	11
S2IN00091	11
S8MI00281	11
S2ND00099	10
S6MN00267	10
S2NM00088	8
S6PA00217	8
S2VA00142	7
S8WA00194	7
S8MN00578	6
S2MA00170	6
S2NE00094	6
S8AZ00197	6

THese go all the way back to 2000 and don't include Joint fundraisers:
P60000270	8
P60000452	8

**Comment by jwchumley** [comment]
Here they are with their committe ids
S2IN00091	C00679340
S2IN00091	C00673293
S2IN00091	C00667501
S2IN00091	C00660639
S2IN00091	C00657569
S2IN00091	C00635300
S2IN00091	C00634360
S2IN00091	C00633925
S2IN00091	C00631960
S2IN00091	C00630202
S2IN00091	C00393652
S2ND00099	C00677450
S2ND00099	C00673293
S2ND00099	C00667501
S2ND00099	C00662916
S2ND00099	C00655662
S2ND00099	C00653469
S2ND00099	C00638296
S2ND00099	C00636811
S2ND00099	C00633578
S2ND00099	C00505552
S2WI00219	C00680066
S2WI00219	C00674192
S2WI00219	C00672527
S2WI00219	C00666917
S2WI00219	C00662916
S2WI00219	C00662114
S2WI00219	C00657569
S2WI00219	C00655662
S2WI00219	C00648071
S2WI00219	C00637165
S2WI00219	C00636803
S2WI00219	C00634352
S2WI00219	C00633925
S2WI00219	C00633578
S2WI00219	C00633073
S2WI00219	C00631960
S2WI00219	C00630467
S2WI00219	C00525295
S2WI00219	C00326801
S6MN00267	C00672527
S6MN00267	C00655662
S6MN00267	C00653857
S6MN00267	C00653485
S6MN00267	C00634352
S6MN00267	C00631705
S6MN00267	C00630806
S6MN00267	C00630467
S6MN00267	C00496539
S6MN00267	C00431353
S6MO00305	C00680066
S6MO00305	C00674192
S6MO00305	C00667501
S6MO00305	C00667337
S6MO00305	C00663153
S6MO00305	C00662114
S6MO00305	C00655670
S6MO00305	C00648238
S6MO00305	C00641084
S6MO00305	C00639203
S6MO00305	C00635300
S6MO00305	C00633925
S6MO00305	C00630616
S6MO00305	C00630467
S6MO00305	C00577148
S6MO00305	C00431304
S6MT00162	C00679340
S6MT00162	C00676817
S6MT00162	C00667501
S6MT00162	C00667493
S6MT00162	C00666032
S6MT00162	C00660357
S6MT00162	C00638296
S6MT00162	C00637165
S6MT00162	C00634360
S6MT00162	C00633925
S6MT00162	C00547679
S6MT00162	C00412304
S6OH00163	C00678094
S6OH00163	C00655688
S6OH00163	C00655670
S6OH00163	C00653485
S6OH00163	C00648089
S6OH00163	C00635987
S6OH00163	C00631960
S6OH00163	C00578609
S6OH00163	C00555342
S6OH00163	C00544296
S6OH00163	C00264697
S8FL00166	C00668814
S8FL00166	C00667501
S8FL00166	C00665265
S8FL00166	C00663153
S8FL00166	C00660639
S8FL00166	C00655670
S8FL00166	C00637165
S8FL00166	C00633925
S8FL00166	C00631960
S8FL00166	C00631796
S8FL00166	C00631705
S8FL00166	C00344051
S8MI00281	C00678094
S8MI00281	C00677468
S8MI00281	C00639203
S8MI00281	C00637173
S8MI00281	C00636803
S8MI00281	C00636191
S8MI00281	C00634352
S8MI00281	C00631960
S8MI00281	C00630467
S8MI00281	C00495580
S8MI00281	C00344473
S8NV00156	C00681460
S8NV00156	C00677468
S8NV00156	C00672840
S8NV00156	C00672519
S8NV00156	C00665265
S8NV00156	C00662114
S8NV00156	C00661314
S8NV00156	C00660639
S8NV00156	C00633925
S8NV00156	C00631960
S8NV00156	C00606939

**Comment by lbeaufort** [comment]
After further research, we discovered that the use case for lifting the restriction is actually a bug - https://app.zenhub.com/workspace/o/fecgov/fec-cms/issues/1656. Closing this issue until we find a use case for removing the 5-committeeID filter.

**Pull request closed without merging**
